### ISSUE TITLE
Env clips action inside the action space

### ISSUE THREAD

**Issue by FrancescoMorri** [Farama-Foundation/PettingZoo#1000]
I've just started using the pistonball environment, and it's printing a Warning for each action of the agents, saying its out of bound:
`[WARNING]: Received an action [-0.98762388] that was outside action space Box(-1.0, 1.0, (1,), float32). Environment is clipping to space`
while it is clearly inside the bounds.

I might be wrong, but it looks like the problems is here: https://github.com/Farama-Foundation/PettingZoo/blob/1c2b566242d3ad5f4fc4bfec00526fe1163eb4d8/pettingzoo/utils/wrappers/clip_out_of_bounds.py#LL40C19-L40C19, where the clipping warning is being called without checking if it is actually needed.

**Comment by pseudo-rnd-thoughts** [comment]
On line 32, it checks that the `not space.contains(action)` so there is an issue
I suspect that the issue is that your action has `dtype=np.float64` which is technically outside the space with `dtype=np.float32`.

@FrancescoMorri Can you confirm this through printing the `dtype` of the action

**Comment by FrancescoMorri** [comment]
Yep, that was the problem. Thanks for the quick reply!
