### ISSUE TITLE
[Question] Flattened action space in chess env

### ISSUE THREAD

**Issue by koliber31** [Farama-Foundation/PettingZoo#1001]
### Question

Hi
I was looking how chess was written in petting zoo and I found action is flatten from 8x8x73 to 4672 and that it can be unflattened using given equations. The problem is i checked them and they give incorrect outputs. Am I doing something wrong?
![obraz](https://github.com/Farama-Foundation/PettingZoo/assets/42122590/890e238b-7819-4e98-8114-5f4a1ce2f6f5)
![obraz](https://github.com/Farama-Foundation/PettingZoo/assets/42122590/fd74081b-7263-4e59-95a5-9753661cfa45)
![obraz](https://github.com/Farama-Foundation/PettingZoo/assets/42122590/15f3770f-19f4-4c04-8a43-6445fcd6dc73)

**Comment by elliottower** [comment]
I believe this is solved in https://github.com/Farama-Foundation/PettingZoo/pull/1004, but @jacob975 can confirm

**Comment by elliottower** [comment]
Looks like it was in this PR instead, but the docstring doesn't follow the convention for which we can check automatically (using `>>>`, gymnasium has examples this way), so I will update it so that the CI checks that these calculations work correctly
