### ISSUE TITLE
[Bug Report] API test test_observation warns for every new game

### ISSUE THREAD

**Issue by BertrandDecoster** [Farama-Foundation/PettingZoo#1039]
### Describe the bug

The code introduced in 1.22.4 for `test_observation` does not seem to work as intended

```
def test_observation(observation, observation_0, env_name=None):
    if not isinstance(observation, np.ndarray) or (
        env_name is not None and env_name not in env_obs_dicts
    ):
        warnings.warn("Observation is not NumPy array")
        return
    ...
```

If your game has an output of type ndarray, but does not belong to a very short list of 10 games in `env_obs_dicts`, there is a message raised `"Observation is not NumPy array"` which is factually false.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by elliottower** [comment]
Thanks for catching this, would you be interested in making a PR to fix this? The or should just be changed to an an, I believe

**Comment by elliottower** [comment]
@BertrandDecoster just pinging you again to see if you wanted to make a PR for it, otherwise someone else can do it
