### ISSUE TITLE
[Question] Is there a convenient way of converting an AECEnv to a Gymnasium Env?

### ISSUE THREAD

**Issue by lcmaier** [Farama-Foundation/PettingZoo#1049]
### Question

I am trying to build a Deep Q Learning system using `stable_baseline3`'s `DQN` class along with the `classic.chess` module from PettingZoo. However, the naive method of attempting to directly run the DQN using PettingZoo's env:
```
import chess
import pettingzoo.classic.chess.chess as zoo
from stable_baselines3 import DQN

env = zoo.env()
# DQN parameters
learning_rate = 0.001
discount_factor = 0.99
exploration_fraction = 0.2
exploration_final_eps = 0.02
model = DQN("MlpPolicy", env, learning_rate=learning_rate, buffer_size=int(1e5), 
            exploration_fraction=exploration_fraction, exploration_final_eps=exploration_final_eps)
```
throws the following error: "ValueError: The environment is of type , not a Gymnasium environment. In this case, we expect OpenAI Gym to be installed and the environment to be an OpenAI Gym environment." 

I am trying to debug this by building a new class that inherits from `gym.Env` but behaves like the `PettingZoo` chess agents. However, I also couldn't help but notice that all of the spaces in `PettingZoo` are gym spaces, so it occurred that there might be a built-in way to solve this problem I'm facing--haven't found one yet though, if one exists. So, does one exist? And if not, is there a generally agreed upon "best" way to do this kind of conversion?

**Comment by elliottower** [comment]
So we've considered making wrappers to convert to Gymnasium (https://github.com/Farama-Foundation/PettingZoo/pull/952) but ultimately decided it was a bit hackey and kind of defeats the point of pettingzoo having multi-agent capabilities, also would only be possible to be one-way in all likelihood (pz -> gymnasium, but not converting back), which is not ideal
