### ISSUE TITLE
[Question] what's the difference between script agent and policy agent?

### ISSUE THREAD

**Issue by Gloriabhsfer** [Farama-Foundation/PettingZoo#1050]
### Question

Hi all:
I am trying to train a multiagent competitive scenario with simple_tag. I have successfully trained the policy for the competitive 2 side. And I have some problems evaluating the training result. I want to embed a policy for one side of my agent (eg: if I want to evaluate my adversary, I will fix the policy for my good agent, and make it move in some velocity obstacle policy. Just make the agent move in some smarter manner rather than just set a random walk from action space). That's called this policy as knowledge policy. The question is when I want to apply the knowledge policy, I set the current obs as input and the policy will return me output in position or velocity, and it's some number that is not inside my action_space. 
I have read the simple_env.py and core.py, there are 2 kinds of agents:
1. policy_agent: return all agents controllable by external policies
2. script_agent: return all agents controlled by world scripts
In core.py, the step is directly applied to script_agent and I can calculate the external force, and action input based on the dynamic policy it has. 
And I have read the code for the original MPE, in their environment.py, the step in an environment controlled by the policy agent. Now I am very confused, in my understanding, I can control the good agent for example, with the knowledge policy, directly control the policy agent with their position and velocity with the estimated position output. So what I need to do is modify the core.py file and control the script agent and policy agent separately. The simple_env will control the agent that is controlled by RL policy. And in core.py, It will control both the RL agent and knowledge agent.
Otherwise, I need to transfer the estimate pos and vel to discrete action space input, but that's a rough controller that will make my knowledge policy now smart as I assume.

Looking forward to your reply.
Gloria

**Comment by elliottower** [comment]
Unfortunately I don't have hardly any experience working with the MPE envs, but if you posted in the #pettingzoo or #rl-questisons channel in our discord (or #mpe2, as we are moving those envs to their own project) I know there are some others who could help out (could just link to this issue)

**Comment by Gloriabhsfer** [comment]
Thanks for your reply. Could you please tell me where is the Discord channel? And if anyone else knows how to solve this question, I can keep the question open.

**Comment by elliottower** [comment]
> Thanks for your reply. Could you please tell me where is the Discord channel? And if anyone else knows how to solve this question, I can keep the question open.

Here's the server https://discord.gg/bnJ6kubTg6 and yeah no worries, definitely fine to keep the question open in case someone has an answer. Just wanted to be clear that I can't offer much help myself. Cheers.

**Comment by elliottower** [comment]
Looking back at this do you think the documentation for MPE environments should be improved? Would be good to know for MPE2 development (@murtazarang )

**Comment by murtazarang** [comment]
Generally, the way people have approached simple_tag (predators vs prey) is by evaluating two different policies trained individually, for each predator and prey, and then evaluating the results. For example, the most common way is to set the _preys_ as a baseline policy of CommNet, and _predators_ defined with the authors novel policy, and the performance is evaluated based on how many _preys_ the _predators_ can capture.

If I were to understand your question, I assume you plan to run your own trained policy for the _predators_ but would like to run a heuristic policy for the _prey_? If this is to be the case, I don't see a need to change the core.py files or any environment files? You can probably just design a controller that accepts the observation space of the _prey_ and work with that?

Let me know if I misunderstood your question?
