### ISSUE TITLE
Mistake in Waterworld documentation provided arguments

### ISSUE THREAD

**Issue by jeremyc1ark** [Farama-Foundation/PettingZoo#1052]
### Describe the bug

I'm referring to the documentation on [this page](https://pettingzoo.farama.org/environments/sisl/waterworld/).
The example given for the arguments is as follows:
waterworld_v4.env(n_pursuers=5, n_evaders=5, n_poisons=10, n_coop=2, n_sensors=20,
sensor_range=0.2,radius=0.015, obstacle_radius=0.2,
obstacle_coord=(0.5, 0.5), pursuer_max_accel=0.01, evader_speed=0.01,
poison_speed=0.01, poison_reward=-1.0, food_reward=10.0, encounter_reward=0.01,
thrust_penalty=-0.5, local_ratio=1.0, speed_features=True, max_cycles=500)

The default argument for `obstacle_coord` is invalid. `obstacle_coord` is supposed to be a list of coordinates rather than just one coordinate. If you try to run waterworld using the configuration above, you it doesn't work. The default argument for `obstacle_coord` should look like this instead:
obstacle_coord=[(0.5, 0.5)]

### Additional context

I apologize that this is labeled as a bug. It should be labeled documentation instead, but I don't know how to change the label.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by elliottower** [comment]
Thanks for pointing this out, will update it real quick and credit you in the commit since you found the bug

**Comment by elliottower** [comment]
Oh looks like the base code itself is correct, will look to see where it needs to be fixed for those docs https://github.com/Farama-Foundation/PettingZoo/blob/7991418998350d1576da53ccad5fa3d33f986a4d/pettingzoo/sisl/waterworld/waterworld_base.py#L33
