### ISSUE TITLE
Can not install pettingzoo 1.24.0 

### ISSUE THREAD

**Issue by uwallgren** [Farama-Foundation/PettingZoo#1053]
### Question

Can not install pettingzoo 1.24.0
running pettingzoo 1.23.1 python 10.9, pip-22.3.1
pip can not find version 1.24.0
I am using window 10 
Can I download this version without pip?

**Comment by elliottower** [comment]
Hi, there was an issue with pypi which prevented it from being uploaded, I am going to re-release on Monday so it should work.

**Comment by elliottower** [comment]
Sorry I’m away for a few days and don’t have access to the farama social media accounts on my laptop so will have to wait till Friday to release but you can always just install from master branch or clone the repo and install locally

**Comment by uwallgren** [comment]
👍

Skickat från min iPhone

**Comment by elliottower** [comment]
Unfortunately there seems to be issues related to web dev causing our docs site to fail, so I won't be able to make a release for a few days until our web developer is able to fix it. The command to install from the most recent master branch though is this:
`pip install 'git+https://github.com/Farama-Foundation/PettingZoo.git'`, you can use that and it will be effectively the same as doing pip install pettingzoo==1.24.0

**Comment by uwallgren** [comment]
Tanks I Will try it


Skickat från min iPhone

**Comment by uwallgren** [comment]
Thanks the installation of 1.24.0 worked fine


Den fre 18 aug. 2023 kl 22:54 skrev Elliot Tower ***@***.***>:
