### ISSUE TITLE
[Question] standardized self-play training?

### ISSUE THREAD

**Issue by DiTo97** [Farama-Foundation/PettingZoo#1067]
Hi all,

I would like to know if there are any guidelines or examples out there (I've already searched the [docs](https://pettingzoo.farama.org/), but couldn't find anything) for the standardized way of creating a customized multi-agent environment for self-play training.

**Comment by elliottower** [comment]
This is highly dependent on the training library or setup you are using, but for reference there are a few self play examples on the RLlib repo using OpenSpiel, I made a pr adapting one of them to work with pettingzoo instead https://github.com/ray-project/ray/pull/33481

if you or anyone wants to create an example training script using CleanRL or SB3 or anything we would love to have it, but currently I don’t have the capacity to make anything myself. 

Generally self play is done with a league, but how you choose the models and structure it is entirely up to you. All you need to do from pettingzoos end is something like “if agent == env.possible_agents[0]” and set the model equal to model A, else set it to the previous checkpoint, etc.

**Comment by DiTo97** [comment]
Could you add a few words on the `if agent == env.possible_agents[0]` statement?

**Comment by elliottower** [comment]
That’s just arbitrarily saying if the agent you’re currently using is the first agent. In a loop you’d do 

for agent in env.agent_iter(): 

And then do different behavior for different agents

**Comment by DiTo97** [comment]
Now it's more clear. Thanks!
