### ISSUE TITLE
[Bug Report] CONTRIBUTING.md guide needs work

### ISSUE THREAD

**Issue by chrisyeh96** [Farama-Foundation/PettingZoo#1094]
### Describe the bug

I tried following the CONTRIBUTING.md guide to run `pytest` but it does not work.

I first did the following, which worked.

```bash
sudo apt update
sudo apt install swig

pip install -e .[all]
```

Then I tried running `pytest` but I received the following error message:

```
/workspaces/PettingZoo $ pytest -v
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n=auto
  inifile: /workspaces/PettingZoo/pyproject.toml
  rootdir: /workspaces/PettingZoo
```

I also tried using `make test-all`:

```
/workspaces/PettingZoo $ make test-all
pytest -v --cov=pettingzoo --cov-report term
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n=auto --cov=pettingzoo --cov-report
  inifile: /workspaces/PettingZoo/pyproject.toml
  rootdir: /workspaces/PettingZoo

make: *** [Makefile:11: test-all] Error 4
```

### System info

I installed PettingZoo in the default GitHub codespace configuration.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by elliottower** [comment]
Oh my fault i forgot to add pytest xdist to the pyproject dependencies, it allows distributed testing. Could you include it in one of your prs?

**Comment by chrisyeh96** [comment]
I think the issue might be instead that CONTRIBUTING.md should say

```bash
pip install -e .[testing,all]
```
instead of

```bash
pip install -e .[all]
```

In [pyproject.toml](https://github.com/Farama-Foundation/PettingZoo/blob/master/pyproject.toml), it seems like the `all` option does not include any of the testing-related dependencies.

I've made a pull request with this change: #1097
