### ISSUE TITLE
[Docs] Incorrect Version Number in Release Notes

### ISSUE THREAD

**Issue by chrisyeh96** [Farama-Foundation/PettingZoo#1098]
### Describe the bug

The release notes on GitHub and on the PettingZoo website list "PettingZoo 1.24.0 Release Notes" under the heading "PettingZoo 1.24.1." This is incorrect. Both should say 1.24.1.

See:
- https://github.com/Farama-Foundation/PettingZoo/releases/tag/1.24.1
- https://pettingzoo.farama.org/release_notes/index.html#release-1-24-0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by elliottower** [comment]
Oh thanks for the heads up on this, just fixed it I believe the site should update accordingly on the next release. Maybe there’s a way to force push changes? @mgoulao

**Comment by elliottower** [comment]
Closing this as it should update at the very least when I do a hotfix (sorry for all the releases, just people pointing out valid issues that went unnoticed like this)
