### ISSUE TITLE
[Question] Parallel API Test

### ISSUE THREAD

**Issue by axelbr** [Farama-Foundation/PettingZoo#1102]
### Question

Why does the api test not allow additional keys (e.g. "common") in the info dictionary?

**Comment by elliottower** [comment]
When converting between parallel and AEC environments we need the keys to be AgentIDs, so we can split an “infos” dict into individual “info” dicts for each agent. 

We made that change somewhat recently because there were users having unexpected issues with different structure for infos, and we thought it would be good to show how the intended use is. But we could always remove it if it really is prohibitive. Why not just add the same “common” info to all AgentIDs?

**Comment by axelbr** [comment]
Ok, I see. Yes, that's one solution. However, I would like to include simulation specific infos there (such as steps/s etc). I think that including a key "common" in the other dicts just to have it in the info dict is cumbersome.

**Comment by elliottower** [comment]
Fair enough, I think we can probably change it to just be a warning and work around it if there are unrecognized keys. Will check with some other core devs to see. I believe Minari is working on more specific requirements for infos so it may be that we want things a bit more standardized, but that’s a future problem not necessary now. Will include this fix in the next minor release if the other devs agree.

**Comment by elliottower** [comment]
Ok the other dev agreed it should be a warning, if you’d like to open a PR changing it feel free otherwise we will when we have time but it may take a little while.

**Comment by axelbr** [comment]
Ok, thanks for your cooperation on that. Yes, i can do it in the next days.

**Comment by elliottower** [comment]
It may be a bit more complicated than just the API test, as I believe it was changed in conversion.py as well. But I think it should be possible to basically have it look through all of the keys which are found in env.possible_agents and then automatically use those in converting from parallel to AEC, or vice versa.

**Comment by elliottower** [comment]
Never mind this still needs to be implemented, I haven't had time yet but maybe someone else could help out

**Comment by elliottower** [comment]
Could you check if the above PR fixes the issue? I think it should but just want to check.
