### ISSUE TITLE
[Bug Report] Incorrect link in documentation

### ISSUE THREAD

**Issue by Jesper-Hustad** [Farama-Foundation/PettingZoo#1113]
### Describe the bug

Link goes to wrong page. Just a typo mistake.

in file [docs/content/environment_creation.md
](https://github.com/Farama-Foundation/PettingZoo/blob/master/docs/content/environment_creation.md?plain=1)on line 9

Current: `[Parallel](/api/aec/)`

Intended: `[Parallel](/api/parallel/)`

### Code example
This would be the corrected version.
```shell
We will walk through the creation of a simple Rock-Paper-Scissors environment, with example code for both [AEC](/api/aec/) and [Parallel](/api/parallel/) environments.
```

### System info

not relevant

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by elliottower** [comment]
Thanks for catching this, if you want to make a quick PR fixing it we would happily accept it, otherwise one of us can do it
