### ISSUE TITLE
[Bug Report] Custom environment tutorial docs broken paths

### ISSUE THREAD

**Issue by rohildshah** [Farama-Foundation/PettingZoo#1122]
### Describe the bug

Hyperlinks 1-4 on the [Custom Environment Tutorials page](https://pettingzoo.farama.org/tutorials/custom_environment/) don't lead anywhere, although the "Next" button in the bottom left leads to the correct page.

Additionally, the all the Custom Environment Tutorial subpages have missing code snippets (screenshot below).
- https://pettingzoo.farama.org/tutorials/custom_environment/1-project-structure/#skeleton-code
- https://pettingzoo.farama.org/tutorials/custom_environment/2-environment-logic/#code
- https://pettingzoo.farama.org/tutorials/custom_environment/3-action-masking/#code
- https://pettingzoo.farama.org/tutorials/custom_environment/4-testing-your-environment/#code

<img width="772" alt="Screenshot 2023-10-25 at 6 48 16 PM" src="https://github.com/Farama-Foundation/PettingZoo/assets/47135708/d9845b99-f6c0-4dc6-955a-61f854b60041">

It seems the code snippets are in the correct place [here](https://github.com/Farama-Foundation/PettingZoo/tree/c65e8947f2b20164dd3bea0a300d42ee9b705594/tutorials/CustomEnvironment), so I'm not sure what's going wrong.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by elliottower** [comment]
These are fixed on the master branch, we've just been waiting on one more PR to make a new release (agileRL is adding another section to their tutorial) but until then you can go to the main branch on the site (see the bottom right menu)
https://pettingzoo.farama.org/main/tutorials/custom_environment/1-project-structure/
