### ISSUE TITLE
[Question] Using a custom gym environment

### ISSUE THREAD

**Issue by shreshth-29** [Farama-Foundation/PettingZoo#1125]
### Question

I have created a custom environment using gymnasium, and I wish to use it with pettingzoo. The existing wrappers are used to convert between AEC and parallel environments, but there isn't any information available on how we can use a gym environment with pettingzoo. What can I do for this?

**Comment by elliottower** [comment]
I believe I commented in discord but there's no easy way to convert, you would have to adapt it manually and make careful consideration of the environment logic. For example, a single player game played with multiple players could mean each player goes sequentially in the same environment, or each at the same time, etc. If one of them terminates the game could end, or it could keep playing. So it's not really possible to make a general purpose wrapper doing this.
