### ISSUE TITLE
[Bug Report] Misuse of warning in Maze Craze

### ISSUE THREAD

**Issue by dm-ackerman** [Farama-Foundation/PettingZoo#1158]
### Describe the bug

The Maze Craze Atari env outputs a warning on init noting that it supports different types of games depending on the creation parameters:

    PettingZoo/pettingzoo/atari/maze_craze/maze_craze.py:106: UserWarning: maze_craze has different versions of the game via the 'game_version' argument, consider overriding.

This seems like an inappropriate use of a warning. Beyond that, it means that `pytest` will always throw warnings for this env when running tests, which isn't ideal.

The information in the warning text is clearly stated in the documentation for the env under 'Environment parameters'.

I think this warning should be removed completely.

### Code example

```shell
from pettingzoo.atari import maze_craze_v3
env = maze_craze_v3.env(render_mode="human")
```

### System info

pip install on Ubuntu 22.04.3 LTS

```
>>> pettingzoo.__version__
'1.24.3'
>>> print(sys.version)
3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0]
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by elliottower** [comment]
Thanks for bringing this up, looks like something that should be cleaned up

**Comment by dm-ackerman** [comment]
OK great. I'll submit a pr to fix it tonight/tomorrow
