### ISSUE TITLE
[Bug Report] TicTacToe: rendering terminal position is wrong

### ISSUE THREAD

**Issue by WolfgangKonen** [Farama-Foundation/PettingZoo#1169]
### Describe the bug

Hello PettingZoo team, 
thanks for providing this awsome software!
When running the minimal code example on TicTacToe, I observe a problem in the human rendering: the last two or three moves are not displayed, see attached PNG
![pzoo_ttt](https://github.com/Farama-Foundation/PettingZoo/assets/8925120/b2ced4b1-4ad3-442a-9eeb-41d0d4c90f80)
The board as printed with "print(env.board)" gives correctly [2, 1, 1, 2, 1, 2, 1, 2, 1], i.e. the board is full, but the rendering shows only the first six moves and thus misses the winning condition

### Code example

```shell
from pettingzoo.classic import tictactoe_v3

env = tictactoe_v3.raw_env(render_mode="human", screen_height=600)
env.reset(seed=42)

for agent in env.agent_iter():
    observation, reward, termination, truncation, info = env.last()

    if termination or truncation:
        print(f"{env.board}")
        print(f"{agent}: reward={reward}, termination={termination}, truncation={truncation}")
        action = None
    else:
        mask = observation["action_mask"]
        # this is where you would insert your policy
        action = env.action_space(agent).sample(mask)

    env.step(action)
env.close()
```

### System info

PettingZoo installed via pip, 
pettingzoo.__version__ = 1.24.3
Windows 11
Python 3.9

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by elliottower** [comment]
I tried to recreate your problem but was unable to reproduce it, could you seed your action spaces as well and try to find seeds which reproduce the problem? When you're printing you may also want to cast the board state into an np.array and reshape to (3,3) and transpose so it looks like the rendered 3x3 board, that way you can more easily see if there's any differences between the rendering and the printed board state.

```
env.action_space(env.possible_agents[0]).seed(0)
env.action_space(env.possible_agents[1]).seed(0)
```

I was able to run it on my end perfectly fine and see the end of games, I tested both using `.raw_env()` as your script does, as well as using `env` (found a bug that the env constructor doesn't take kwargs so I made a PR fixing that).

The one thing I can think of is it may be a weird issue related to running pygame in pycharm, try running in the command line as well to see if there is any difference. Feel free to toy around with the code yourself if you'd like as well, if you find what could be potentially produce it you can make a PR as well (or I can do it), I just can't think of anything myself as the rendering code looks pretty simple.

**Comment by WolfgangKonen** [comment]
Dear Elliot, thanks for the super-fast response and the testing on your side. 
I tried what you suggested: start w/o PyCharm >> same behaviour. Start with seeded action space >> same behaviour, only reproducible. Then I played a little bit around with the rendering code, verified that every render() call was executed to the end, which is the case. I was suspicious, it might be something near pygame.display.update().

The very strange 'solution': When I changed the line 
          self.clock.tick(self.metadata["render_fps"])
to
          self.clock.tick(2)
(or if I - equivalently - set render_fps in the metadata to 2), the error is gone, every action is rendered to the end, only a bit faster. I have no idea why this is the case, but perhaps - if others have similar issues - it could be an option to make render_fps a constructor argument like screen_height is. Might be a nice feature anyway.
(From my observations: FPS < 1.4 cause the error on my machine, FPS > 1.6 have it cured - at least in the test trials I did)

I can perfectly live with this 'solution', so you may close this issue. Thanks again!

**Comment by elliottower** [comment]
That's bizarre about the render fps, if you can find something on pygame's side (or maybe try a new version of pygame? we have 2.3 pinned iirc, there is now a 2.5.2) confirming that there should be some issues with doing clock tick for 1 second but I imagine there isn't. 

I've thought about adding the render_fps as an input argument but I'd want to do it for all of the environments at the same time to be consistent. I think for now it is probably best to stick with things as they are though, as Gymnasium and all other environments pretty much have their rendering FPS specified in the environment metadata. Arguably the kwargs for screen size (which I added) shouldn't be there for the same reason, but it was a useful quality of life feature that I needed to have access to at the time. To be fair though, neither of those should affect training as you generally would want to use the `rgb_array` render mode in the case that you are analyzing visual input (e.g., with CNNs), can't imagine anyone would want to do some sort of training with the live pygame window. 

Anyways glad you found a solution that works and are satisfied, I'll probably see if any other devs have thoughts on the idea of doing a dynamic render FPS in the future but that wouldn't be a big priority in all likelihood
