### ISSUE TITLE
[Bug Report] tictactoe_v3 - Render mode "ansi" renders the pygame screen

### ISSUE THREAD

**Issue by RicardoRibeiroRodrigues** [Farama-Foundation/PettingZoo#1187]
### Describe the bug

When using the 'ansi' render_mode in tictactoe_v3 , despite intending solely for the game loop backend to operate, the environment still renders the pygame screen. This complicates automated testing procedures within the environment (testing algorithms for the environment).

### Code example

```shell
# Reference: https://pettingzoo.farama.org/environments/classic/tictactoe/
from pettingzoo.classic import tictactoe_v3


def play_random_agent(agent, obs):
    x = env.action_space(agent).sample()
    while obs["action_mask"][x] != 1:
        x = env.action_space(agent).sample()
    return x

env = tictactoe_v3.env(render_mode="ansi")
env.reset()

not_finish = True
while not_finish:
    for agent in ["player_1", "player_2"]:
        observation, reward, termination, truncation, info = env.last()
        if termination or truncation:
            not_finish = False
            break

        if agent == "player_1":
            action = play_random_agent(agent, observation)
        else:
            action = play_random_agent(agent, observation)

        env.step(action)
```

### System info

- Installed with pip
- Version = '1.24.3'
- "Ubuntu 22.04.3 LTS"
- Python 3.10.12

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by elliottower** [comment]
ANSI rendering was disabled a while ago when everything was moved from text rendering to pygame, but if anywhere in the docs still has it we can remove that
