### ISSUE TITLE
[Bug Report] Potential information mismatch in the Simple World Comm environment

### ISSUE THREAD

**Issue by duartejeremias** [Farama-Foundation/PettingZoo#1207]
### Describe the bug

I think there is an information mismatch between the [Simple World Comm documentation page](https://pettingzoo.farama.org/environments/mpe/simple_world_comm/) and the [source code](https://pettingzoo.farama.org/_modules/pettingzoo/mpe/simple_world_comm/simple_world_comm/#raw_env) in two ocasions.

More precisely:

- When presenting the format of the good agent observations, it's written that:

> Good agent observations: `[self_vel, self_pos, landmark_rel_positions, other_agent_rel_positions, other_agent_velocities, self_in_forest]`

However, in the source code page, when returning the observations for the good agent, the `self_in_forest` observation is placed out of order:
`return np.([agent.state.p_vel] + [agent.state.p_pos] + entity_pos + other_pos + in_forest + other_vel)`

- When presenting the format of the leader adversary agent observations, it's written that:

> Adversary leader observations: `[self_vel, self_pos, landmark_rel_positions, other_agent_rel_positions, other_agent_velocities, leader_comm]`

Howerver, in the source code page, the `in_forest` observation is also being returned.

### Code example

```shell
if agent.leader:
            return np.concatenate(
                [agent.state.p_vel]
                + [agent.state.p_pos]
                + entity_pos
                + other_pos
                + other_vel
                + in_forest
                + comm
            )
        else:
            return np.concatenate(
                [agent.state.p_vel]
                + [agent.state.p_pos]
                + entity_pos
                + other_pos
                + in_forest
                + other_vel
            )
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by dm-ackerman** [comment]
Good catch. If you want to submit a pull request to fix it, that'd be great. Otherwise, I (or someone else) will get to it eventually.
I think changing the docs to match the code (as opposed to changing the code to match the docs) is the preferred approach.

**Comment by pandyah5** [comment]
I can work on this issue and submit a PR!

**Comment by pandyah5** [comment]
@dm-ackerman Just pushed a PR to update the docs as you have suggested. It's my first time contributing here so let me know if the PR needs more polishing. Cheers!
