### ISSUE TITLE
[Proposal] Adding a video tutorial on how to contribute to PettingZoo

### ISSUE THREAD

**Issue by pandyah5** [Farama-Foundation/PettingZoo#1221]
### Proposal

I've created a concise video contribution guide for the PettingZoo repository to assist future contributors in understanding the project's workflow and standards more effectively. The video covers setup, coding guidelines, finding issues, creating branches, testing, and submitting pull requests.

If the maintainers find it useful, we could add this to the README to help future contributors.

The tutorial: https://youtu.be/TyYngFeHakQ?si=AVf2VhYZkoFHxzqD

### Motivation

While the written documentation outlines the technical details and guidelines effectively, a video guide provides a visual, step-by-step walkthrough that complements different learning styles and simplifies the onboarding process.

### Pitch

Add the link to the README.md or CONTRIBUTING.md? The latter might be better

### Additional context

I personally found the setting up process of a repository the most daunting part of Open-Source contribution. When I started contributing I would look for such tutorials but could seldom find them, so now that I am better at it I want to make these tutorials to help others :)

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by jkterry1** [comment]
Hey,

Thank you so much for creating the guide! I'm not certain that this is a perfect fit for including in the official documentation, but I really appreciate your work on this and I'll definitely send it to people if it comes up.
