### ISSUE TITLE
Examples of vairable agents

### ISSUE THREAD

**Issue by PingH129** [Farama-Foundation/PettingZoo#1224]
### Question

I am using PettingZoo to implement an MARL env. However, variable agents are needed in my env. Some agents may die and dispear and some new agents may generate in each reset. The _Variable Numbers of Agents (Death)_ section of the [PettingZoo Documentation](https://pettingzoo.farama.org/) only tells us that agents can die and generate during the course of an environment. However, these is no concrete exmaples. 
 Could you please provide an example how to address this in the PettingZoo Env?
Thanks very much for your great jobs.

**Comment by jkterry1** [comment]
Hey,

You'll find examples of this present in the environments in this repo: https://github.com/Farama-Foundation/MAgent2

**Comment by PingH129** [comment]
Thanks very much!
