### ISSUE TITLE
[Proposal] Adding Shogi to Classic

### ISSUE THREAD

**Issue by jkterry1** [Farama-Foundation/PettingZoo#283]
The one environment that I'd really like to be in PettingZoo, but isn't, is Shogi. The way to do this would be to use python-shogi for the game logic, and have the observation/action spaces as DeepMind did with AlphaZero. Contributions for this would be appreciated.

**Comment by jkterry1** [comment]
Per #480 this should likely be done via the openspiel env.

**Comment by elliottower** [comment]
This would be cool to have, but we would need to have graphics made for it. Not sure if it's a high priority or not.

**Comment by elliottower** [comment]
Closing this as Jordan has said it's not a huge priority right now
