### ISSUE TITLE
Possible to teams of agents in a ParallelEnv environment?

### ISSUE THREAD

**Issue by apigott** [Farama-Foundation/PettingZoo#375]
Maybe this is a documentation question because it seems like this would've been implemented but I can't tell if any of the PettingZoo MAgent examples do this already, and I can't tell if this use of black_death is going to cause problems.

I have a problem where I want agents to act in teams that alternately take actions. The best I can come up with is to initialize a set of models on a black_death enabled Parallel Environment and let each of the models learn a "team" of agents while ignoring others. I think it makes sense to do this in 2 separate agents because otherwise 50% of the model's data will be gibberish from time that an agent's team is "sleeping".

Clearly AEC could handle the teams aspect but AFAIK would not preserve the distributed agents of ParallelEnv. Would appreciate input on where to look for examples of this if it's already been implemented. Thanks!

```
from stable_baselines3.ppo import MlpPolicy
from stable_baselines3 import PPO
import supersuit as ss
from pettingzoo import ParallelEnv
import pandas as pd
import random
import string
import numpy as np
import gym

class MyEnv(ParallelEnv):
    def __init__(self, grid):
        self.grid = grid
        self.agents = list(self.grid['name'])
        self.possible_agents = self.agents[:]

        self.observation_spaces = {agent: gym.spaces.Box(low=-1*np.ones(1), high=np.ones(1)) for agent in self.agents}
        self.action_spaces = {agent: gym.spaces.Box(low=-1*np.ones(1), high=np.ones(1)) for agent in self.agents}

        self.metadata = {'render.modes': [], 'name':"my_env"}
        self.ts = 0

    def reset(self):
        self.ts = 0
        return self.state()

    def state(self):
        obs = self.grid.set_index('name').to_dict()['observation']
        obs = {k: np.array([v]) for k,v in obs.items()}
        return obs

    def get_reward(self):
        rewards = {agent: float(self.grid.loc[self.grid.name==agent, 'observation']) for agent in self.agents}
        return rewards

    def get_done(self):
        dones = {agent: False for agent in self.agents}
        return dones

    def get_info(self):
        infos = {agent: {} for agent in self.agents}
        return infos

    def step(self, action_dict):
        # assign an env name just so I can keep track
        if self.ts == 0:
            self.grid['env_name'] = pd.Series([''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(5))])

        # select the agents that will be active this round
        self.agents = self.possible_agents[(self.ts%2)::2]
        for agent in action_dict.keys():
            self.grid.loc[self.grid.name==agent, 'observation'] = action_dict[agent]

        self.ts += 1

        # for debugging purposes
        print(self.grid)
        return self.state(), self.get_reward(), self.get_done(), self.get_info()

if __name__=="__main__":
    import multiprocessing
    import sys

    multiprocessing.set_start_method("fork")

    nagents = 4
    agents = [''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(5)) for _ in range(nagents)]
    df = pd.DataFrame({'name':agents,'observation':[np.random.uniform(0,2) for _ in range(nagents)]})

    env = MyEnv(df)
    env = ss.black_death_v1(env)
    env = ss.pettingzoo_env_to_vec_env_v0(env)
    env = ss.concat_vec_envs_v0(env, 4, num_cpus=4, base_class='stable_baselines3')

    models = []
    models += [PPO(MlpPolicy, env, verbose=2, gamma=0.999, n_steps=1, ent_coef=0.01, learning_rate=0.00025, vf_coef=0.5, max_grad_norm=0.5, gae_lambda=0.95, n_epochs=4, clip_range=0.2, clip_range_vf=1, tensorboard_log="./ppo_test/")]
    models += [PPO(MlpPolicy, env, verbose=2, gamma=0.999, n_steps=1, ent_coef=0.01, learning_rate=0.00025, vf_coef=0.5, max_grad_norm=0.5, gae_lambda=0.95, n_epochs=4, clip_range=0.2, clip_range_vf=1, tensorboard_log="./ppo_test/")]
    for _ in range(10): # timesteps
        for model in models:
            model.learn(1)
    # multiprocessing pool hangs but I'm not sure where to close it
    print('learning done')
```

**Comment by weepingwillowben** [comment]
So some considerations to take into account while designing your solution are:
What environment are you trying to use? Is it a custom environment or the MAgent environment itself? How many agents does your environment have? Does your environment natively have turn based behavior? Some considerations, depending on the answers are 1) Most environments, including MAgent, don't benefit from multiprocessing as they are already fast. 2) There is little practical benefit to parallelizing over teams if the number of agents per team is small 3) There is an AEC vector API [in supersuit](https://github.com/PettingZoo-Team/SuperSuit/blob/master/supersuit/aec_vector/base_aec_vec_env.py) that is reasonably well tested, if not super well documented and designed for running multiple AEC environments in parallel. Please raise an issue if you do not understand that API. 

Are you set on using stable baselines? Stable baseline's vector environment API will not support this turn based approach very well. I would recommend writing your own code or use a different framework like RLLib that supports this turn based approach natively.
