### ISSUE TITLE
Warnings in CI tests to resolve

### ISSUE THREAD

**Issue by jkterry1** [Farama-Foundation/PettingZoo#498]
Looking at CI, there are several warnings in pettingzoo that likely should be addressed:

There's this:

test/pytest_runner.py::test_module[classic/texas_holdem_no_limit_v5-pettingzoo.classic.texas_holdem_no_limit_v5]
  /opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32
    warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))

Then there's a ton of these warnings in CI tess

test/pytest_runner.py: 63 warnings
  /home/runner/work/PettingZoo/PettingZoo/pettingzoo/utils/wrappers/base.py:51: UserWarning: The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.
    warnings.warn("The `observation_spaces` dictionary is deprecated. Use the `observation_space` function instead.")

Then there's this:

test/pytest_runner.py::test_module[sisl/waterworld_v3-pettingzoo.sisl.waterworld_v3]
  /opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/gym/spaces/box.py:143: UserWarning: Casting input x to numpy array.
    warnings.warn("Casting input x to numpy array.")

Then finally there's this

test/pytest_runner.py::test_module[sisl/pursuit_v3-pettingzoo.sisl.pursuit_v3]
  /home/runner/work/PettingZoo/PettingZoo/pettingzoo/utils/env.py:89: UserWarning: Your environment should override the action_space function. Attempting to use the action_spaces dict attribute.
    warnings.warn("Your environment should override the action_space function. Attempting to use the action_spaces dict attribute.")

**Comment by elbamos** [comment]
You asked me to take a look at this... the only one of the warnings I'm able to replicate in pytest concerns the cast of x to a numpy array by waterworld. I dug into the observation_space issue, and couldn't find any code that looks like it would cause that warning to arise. 

Can you advise about where you're seeing these? In the meantime I will look at the waterworld-cast issue.

**Comment by jkterry1** [comment]
You can see these in the github actions console output when CI runs on any PR. Some may already be fixed or something, this is a slightly old issue.

**Comment by benblack769** [comment]
I think these have all been fixed by now. I'll close this until you can see them again.
