### ISSUE TITLE
Waterworld has some sort of odd catastrophic bug

### ISSUE THREAD

**Issue by jkterry1** [Farama-Foundation/PettingZoo#520]
So the rendering of all the better policies in waterworld is in here: https://drive.google.com/drive/folders/1SXdQjwoKOJoakeeliOA-1OtLzN8OvddJ?usp=sharing

In every single best policy found, the agents cling to walls and then all huddle in one corner after bouncing around the walls a bit (except for one where the agents bounced around on a wall instead of on a corner). Something is obviously very wrong with the environment for this behavior to be occurring like this, especially so universally. I have no clear idea what.

**Comment by jkterry1** [comment]
Ryan says he tested observations incredibly thoroughly, meaning it's either actions or rewards, but random actions don't do this, so presumably something is wrong with rewards.

**Comment by elbamos** [comment]
Can you clarify what makes you conclude that the policies learned are suboptimal, and what you feel an optimal policy should look like?

I examined those gifs. It looks to me like the agents are (correctly) learning a ambush-feeding policy. They hide in the corner together, where the probability of being hit by poison is very low, wait for food particles to enter their sensory range, and then leave the corner to capture the food and return to the corner. This looks like a feeding strategy that’s often seen in nature and I’m not sure what the problem is. 

If the goal is to not have them group in the corners, then the issue seems to be that’s it’s almost impossible for the poison to drift into those corners.

**Comment by jkterry1** [comment]
So, I think that this is a local minima because the policies aren't causing the agents to run around grabbing food, which surely would perform better. It may be the case that this is an impossible policy for agents to learn, but I think that the issue is ultimately that the environment was poorly designed.

For a bit of history on this environment, it was pulled in from a state of very bad maintenance after being hacked together at a lab in Stanford in the super early days of PettingZoo and was very lightly fixed and documented over time. As best as I can tell, no one ever really made a concerted effort to learn this environment until I tried for a project I've been working in (it's not one of our more popular environments, perhaps due to the issues I'm finding here).

With this in mind:
-I think that the environment never ending and food not being consumed is strange, and if possible I'd like to change the environment mechanics for this to be the case. I originally thought it should be the case that the environment should be something with a time penalty and early termination, but I don't think that this is the case.
-I'd like the environment to be designed so that good behaviors the environments to involve complexity and strategy, which is something much more difficult and interesting to learn than to just hide in the corner. Perhaps the poison reward is too high, the agents can't move fast enough, or so on.

As far as the specific changes to the environment that should be made, I'm completely open to suggestions. If you'd like to discuss this over a call, and discuss some the term plans for PettingZoo/Gym and your interests here in general, we can do that. You've been doing enough for PettingZoo that I'd love to meet.

As far as the general direction for fixing this, what we'd want to do is agree on a new design strategy, implement it on a fork, I can try learning it and see if it learns in a reasonable way any without bugs, fix it, and then repeat the process of learning and fixing until the environment looks to be working.

**Comment by jkterry1** [comment]
Additionally, the local reward argument need to be replaced with a boolean (like what was done with pursuit recently), this needs to be fixed (https://github.com/Farama-Foundation/PettingZoo/issues/541#issuecomment-968271662) and https://github.com/Farama-Foundation/PettingZoo/issues/525 should be fixed (though it's a super simple fix).

**Comment by benblack769** [comment]
@elbamos My hypothesis is that this "hide in the corners" strategy is a local optimum, not a global optimum. I belive that a global opimum can be found via a better MARL algorithm than independent learning.

**Comment by jjshoots** [comment]
For anyone else seeing this issue, a major fix and change of the waterworld environment is in the works.
