### ISSUE TITLE
[suggestion] Add aec_wrapper_fn() to utils.conversions

### ISSUE THREAD

**Issue by WillDudley** [Farama-Foundation/PettingZoo#529]
### Motivation
I wish to refactor my custom MARL environment to a more standardised, clean format, so I am attempting to convert it to PettingZoo's format. My custom environment is intuitively a parallel environment, so I have refactored it as such. Thus, I want to utilise the tests to sanity-check my environment.

### Issue
`seed_test()` fails with parallel env_fn, unlike aec_env_fn - the following is raised: `AttributeError: 'raw_env' object has no attribute 'agent_iter'`. Additionally, whilst there is a provided way to convert aec_env_fn -> parallel_env_fn [here](https://github.com/Farama-Foundation/PettingZoo/blob/119abbf08d823e32e1ea7820ff17fb8895a37ca7/pettingzoo/utils/conversions.py#L10), there is no vice-versa. Hence it is not possible to easily seed test native parallel envs.

### Proposed solutions

1. Raise an error when passing a parallel_env_fn into `seed_test()`.
2. Add the following to [utils.conversions](https://github.com/Farama-Foundation/PettingZoo/blob/119abbf08d823e32e1ea7820ff17fb8895a37ca7/pettingzoo/utils/conversions.py):

```
def aec_wrapper_fn(env_fn):
    def aec_fn(**kwargs):
        env = env_fn(**kwargs)
        env = from_parallel_wrapper(env)
        return env
    return aec_fn
```

### Notes

I'd submit a PR myself, but I am not too familiar in writing tests.

I am fairly new to PettingZoo so please forgive if this is an inappropriate suggestion (eg. custom environments should always be written as AEC)

**Comment by benblack769** [comment]
Made a PR to resolve this #532
