### ISSUE TITLE
Parallel API Tests Do Not Allow Respawning Agents

### ISSUE THREAD

**Issue by jsuarez5341** [Farama-Foundation/PettingZoo#530]
The Parallel API tests (https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/test/parallel_test.py) contain several tests for obs/rewards/dones/infos after an agent is marked done.

`assert set(obs.keys()) == (set(live_agents)), "agents should not be given an observation if they were done last turn"`                                        

Environments can respawn agents as soon as they die. This is true in Neural MMO (neuralmmo.github.io), which I'm currently updating to support pettingzoo. Even worse, these tests check if agents are given an observation when they were done _last_ turn -- meaning that you have to wait two timesteps before respawning.

Deleting these tests outright would decrease useful coverage for most environments. Two possible solutions:

1. Add an optional allow_respawn flag to the API tests
2. Enforce that each agent have a unique ID and clarify the documentation surrounding possible_agents

I am using the Parallel API as a reference here as the AEC model is not sensible for my env, but it is possible the same issue exists in the main API. I could not tell at a glance -- it appears the test coverage is different and much more thorough there.

One quick question while I'm at it: does pettingzoo expect an obs on the timestep an agent is marked done?

**Comment by benblack769** [comment]
@jsuarez5341 Improved the error message on resurection for parallel environments in #531 . Note that the aec environment tests already covered that case explicitly

As for your question, yes, the parallel pettingzoo API does require that there is an observation at the same timestep an agent is done.
