### ISSUE TITLE
Possible KAZ bugs

### ISSUE THREAD

**Issue by SonSang** [Farama-Foundation/PettingZoo#535]
1. Zombies are killed without any reason
![hyperparameter_3_run_1 (1) (1)](https://user-images.githubusercontent.com/20263232/140653694-2bdf8143-6418-494a-b6d9-3e65c727b673.gif)

2. Knights are freezed
![hyperparameter_15_run_8](https://user-images.githubusercontent.com/20263232/140653753-eb327e62-8e2c-40c5-ba99-6b0f2653a273.gif)

**Comment by jkterry1** [comment]
(note how the night is frozen while the zombie is still moving- the gif isn't just pausing to restart or something)

**Comment by jkterry1** [comment]
#602 fixes the second bug described here

**Comment by jkterry1** [comment]
#602 fixes both actually, _we think_
