### ISSUE TITLE
$400 bounty for fixing and learning near optimal policy with Stable Baselines 3 in Waterworld environment

### ISSUE THREAD

**Issue by jkterry1** [Farama-Foundation/PettingZoo#541]
Hey,

If anyone is able to provide me Stable Baselines 3 based learning code that can learn near optimal policies (e.g. solve) the [Waterworld](https://www.pettingzoo.ml/sisl/waterworld) environment once it's fixed enough to be a reasonable environment that learning works in, I will pay you a bounty of $400. Example SB3 code for similar pettingzoo environments is available [here](https://towardsdatascience.com/multi-agent-deep-reinforcement-learning-in-15-lines-of-code-using-pettingzoo-e0b963c0820b) and [here](https://github.com/jkterry1/Butterfly-Baselines). If you iteratively fix the environment and learning code enough that hyperparameter tuning appears to be needed, I can run automated hyperparameter tuning code for you in between debugging stages if you need it and talk to me. 

A few notes:
-The learning code has to generally work across multiple runs, not just one seed
-I'm the final ruler if there are any disputes about the terms of this bounty (e.g. I reserve the right to split the bounty between two people if this situation warrants this or god knows what else may come up)
-Doing this may also require minor changes/fixes to to SuperSuit, or to SB3 itself
-The list of currently known bugs to explore and design failures for waterworld can be found here (https://github.com/Farama-Foundation/PettingZoo/issues/520), along with thoughts on what general changes should be made
-If you currently work for me you are not eligible for the prize
-The origin of this bounty is that Waterworld as an environment clearly needs a lot of iterations of fixes and learning to become a fully working and useful environment per the issue above, and the motivation for creating the bounty for this is that I don't have the time to do this right now. If this works out I plan to create similar bounties for other PettingZoo environments (KAZ, Prospector and the MAgent environments), which would have different rules and very different technical challenges in completing them (e.g. they're hard to learn, not buggy). Waterworld has seemingly remained in this buggy state despite how much PettingZoo has been used because it's not a profoundly interesting environment on it's own, it's only useful if you're trying to benchmark something a huge set of cooperative environments (which is why I starting used it and ran into all these issues). However, I do think that it still has enough value to be worth fixing
-If you want to try this you don't need to contact me or anything, you can just start writing code
-Feel free to leave a comment here if you have any questions

**Comment by jkterry1** [comment]
One other fix to claim this prize is removing the local reward argument, like was recently done for pursuit environment (which is also in SISL)

**Comment by araffin** [comment]
this https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/sisl/waterworld/waterworld_base.py#L46
already look like an issue (see warnings from the env checker...), it seems that `pursuer_max_accel=0.01` which is a bad news: https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html#tips-and-tricks-when-creating-a-custom-environment

**Comment by jkterry1** [comment]
Ya, that should probably be fixed too

**Comment by jkterry1** [comment]
the local reward argument also needs to be replaced with a boolean like what's been done with pursuit and is going to be done with multiwalker

**Comment by jkterry1** [comment]
(this is currently on hold as me and someone else are starting to work on this again ourselves)

**Comment by jkterry1** [comment]
Closing in favor of #520
