### ISSUE TITLE
API link on website broken

### ISSUE THREAD

**Issue by stefanbschneider** [Farama-Foundation/PettingZoo#549]
I just noticed a small bug on the PettingZoo website:

The website's API button links to https://www.pettingzoo.ml/API, which does not exist and leads to a 404 error.
The correct link should be https://www.pettingzoo.ml/api, i.e., in lower case.

---

I just saw, this PR is fixing the issue: https://github.com/Farama-Foundation/PettingZoo/pull/545

**Comment by jkterry1** [comment]
merged and released, sorry about the delay there :)
