### ISSUE TITLE
Import env errors

### ISSUE THREAD

**Issue by mvadrev** [Farama-Foundation/PettingZoo#550]
Hello,

I am new to MARL and want to create custom parallel env in PettingZoo and wanted to play with it. I am getting the following import error when attempting to get the environments.

`
from pettingzoo.butterfly import pistonball_v4
env = pistonball_v4.env()
`

`
ImportError: cannot import name 'pistonball_v4' from 'pettingzoo.butterfly'
PS C:\Users\mvadr\Desktop\gym> 

`

**Comment by benblack769** [comment]
For me, the code:

```
from pettingzoo.butterfly import pistonball_v4 
env = pistonball_v4.env()
```

Work just fine on pettingzoo==1.13.1. Could you say which version of pettingzoo you are running?

**Comment by mvadrev** [comment]
Hi Thanks for your reply. I am using Colab and installed 1.13.1 with pip but getting the following error.

![image](https://user-images.githubusercontent.com/13560125/143515736-e7334a40-8c3e-4d58-9e0d-7be8ffea3987.png)

**Comment by benblack769** [comment]
I was able to reproduce the problem in colab. 

A weird, but effective workaround is to do this:

```
import pettingzoo.butterfly.pistonball_v4 as pistonball_v4
pistonball_v4.env()
```

I have no idea why this works and not the earlier statement. Very mysterious. Maybe colab has some special python version they deploy?

**Comment by mvadrev** [comment]
It is strange indeed but I can confirm I get the same error on my local machine too. Thanks for the fix though!

**Comment by benblack769** [comment]
Out of curiosity, which python version are you running? I haven't tested it with python 3.9 or 3.10 yet.

**Comment by mvadrev** [comment]
Hey  Ben. its 3.9.9

**Comment by benblack769** [comment]
Thanks. I'll try to install a python3.9 environment and try to fix this soon.

**Comment by nikhilweee** [comment]
Can confirm the same. I'm running the [13lines](https://github.com/Farama-Foundation/PettingZoo/blob/968b492b250a935f9a43e9a3f110bc8de280a4cc/tutorials/13_lines.py) tutorial with `pettingzoo 1.12`, `python 3.8.12`, and `conda 4.11` on Apple M1.
```
$ python 13lines.py
Traceback (most recent call last):
  File "13lines.py", line 3, in <module>
    from pettingzoo.butterfly import pistonball_v4
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/rl/lib/python3.8/site-packages/pettingzoo/butterfly/__init__.py", line 5, in __getattr__
    return depricated_handler(env_name, __path__, __name__)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/rl/lib/python3.8/site-packages/pettingzoo/utils/deprecated_module.py", line 42, in depricated_handler
    raise ImportError(f"cannot import name '{env_name}' from '{module_name}'")
ImportError: cannot import name 'pistonball_v4' from 'pettingzoo.butterfly'
```

**Comment by benblack769** [comment]
@nikhilweee If you are using pettingzoo 1.12, this might be expecected behavior---if I'm not mistaken, then that version of pettingzoo contains pistonball_v3, not pistonball_v4. 

Try to see if the fix above `import pettingzoo.butterfly.pistonball_v4 as pistonball_v4` fixes your issue, and if not if impporting 

`from pettingzoo.butterfly import pistonball_v3` fixes your issue

**Comment by jkterry1** [comment]
@benblack769 I just got this bug installing the newest version of pettingzoo on pypi in a virtualenv on GCP too. This is real

**Comment by jkterry1** [comment]
using 1.13.1

**Comment by capyun** [comment]
hello, i am using python3.8, pettingzoo 1.14.0,
and i get some error:

env = pistonball_v4.parallel_env(n_pistons=20, time_penalty=-0.1,
    this raise DeprecatedEnv(f"{name}_v{old_version} is now deprecated, use {name}_v{new_version} instead")
pettingzoo.utils.deprecated_module.DeprecatedEnv: pistonball_v4 is now deprecated, use pistonball_v5 instead

when i use v5
from pettingzoo.butterfly import pistonball_v5
    this raise ImportError(f"cannot import name '{env_name}' from '{module_name}'")
ImportError: cannot import name 'pistonball_v5' from 'pettingzoo.butterfly'

**Comment by jkterry1** [comment]
So, for all future travelers, this issue comes up when upgrading Pettingzoo, for reasons we aren't able to figure out. IF you just uninstall/reinstall, the problem goes away
