### ISSUE TITLE
Problems encountered using action_mask

### ISSUE THREAD

**Issue by zhou163** [Farama-Foundation/PettingZoo#551]
The error message is as follows：

TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_42/701851218.py in <module>
      7 env = to_parallel(env)
----> 8 env = ss.pettingzoo_env_to_vec_env_v1(env)
     9 env = ss.concat_vec_envs_v1(env, 4, num_cpus=4, base_class='stable_baselines3')
      

/opt/conda/lib/python3.7/site-packages/supersuit/vector/vector_constructors.py in pettingzoo_env_to_vec_env_v1(parallel_env)
     64     assert isinstance(parallel_env, ParallelEnv), "pettingzoo_env_to_vec_env takes in a pettingzoo ParallelEnv. Can create a parallel_env with pistonball.parallel_env() or convert it from an AEC env with `from pettingzoo.utils.conversions import to_parallel; to_parallel(env)``"
     65     assert hasattr(parallel_env, 'possible_agents'), "environment passed to pettingzoo_env_to_vec_env must have possible_agents attribute."
---> 66     return MarkovVectorEnv(parallel_env)

/opt/conda/lib/python3.7/site-packages/supersuit/vector/markov_vector_wrapper.py in __init__(self, par_env, black_death)
     27         self.num_envs = len(par_env.possible_agents)
     28         self.black_death = black_death
---> 29         self.obs_buffer = np.empty((self.num_envs,) + self.observation_space.shape, dtype=self.observation_space.dtype)
     30 
     31     def seed(self, seed=None):

TypeError: can only concatenate tuple (not "NoneType") to tuple

How should I fix the error

**Comment by zhou163** [comment]
observation_spaces:       

 self.observation_spaces  = dict(zip(self.agents, [Dict({
            'observation': Box(low=0, high=1, shape=(32, 32, 20), dtype=np.float32),
            'action_mask': Box(low=0, high=1, shape=(6,), dtype=np.float32)
        })  for _ in enumerate(self.agents)]))

**Comment by benblack769** [comment]
Unfortunately, this is a current limitation with the pettingzoo_env_to_vec_env_v1 and concat_vec_envs_v1 wrappers. They do not work with action masks at the moment. To do so would require doing something along the lines gym does here: https://github.com/openai/gym/blob/master/gym/vector/utils/numpy_utils.py#L10 and to support multiprocessing, some additional logic needs to be added. 

I'll keep this issue open as a feature request.

**Comment by zhou163** [comment]
thank you for your reply
I want to reduce the training range through action_mask
In many cases, some actions are invalid in the game.

Can this be restricted when the action is generated?

**Comment by benblack769** [comment]
Unfortunately, the action mask is the proper way of handling this (paper decribing the issues in detail here: https://arxiv.org/abs/2006.14171).

If you want to use stable baselines then hopefully, once supersuit support for dict spaces is added in supersuit, you can use the MaskablePPO implemetation in SB3 contrib here: https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/tree/master/sb3_contrib/ppo_mask (more commentary about the implementation in SB3 here: https://github.com/hill-a/stable-baselines/issues/351).

The main reasonable alternative is to just penalize illegal actions in your environment and hope that your neural network can quickly learn not to play them.

**Comment by zhou163** [comment]
I want to train the game agent will have many deaths and spawns
Does _cumulative_rewards store final agent rewards?

Will the agent die rewards disappear?

I see the following code:
def _was_done_step(self, action):
       .......
       del self._cumulative_rewards[agent]


This indicates that the reward record will be removed if the agent dies?

**Comment by zhou163** [comment]
> I want to train the game agent will have many deaths and spawns Does _cumulative_rewards store final agent rewards?
> 
> Will the agent die rewards disappear?
> 
> I see the following code: def _was_done_step(self, action): ....... del self._cumulative_rewards[agent]
> 
> This indicates that the reward record will be removed if the agent dies?

**Comment by benblack769** [comment]
If an agent dies, then, is respawned, and can continue gaining reward afterwards, the best way to model that is to just not have it be done. Instead, you can penalize the death with some reward shaping and have the agent continue to be alive, but have its actions be useless, while it is respawning.  

This method is used in the Atari environments, such as Joust, where agents lose lives and respawn, but are not done until they can no longer revive.

**Comment by benblack769** [comment]
The remaining issue is being resolved by https://github.com/Farama-Foundation/SuperSuit/pull/122, more comments can be added to that PR.
