### ISSUE TITLE
missing default config in PettingZoo/tutorials/render_rllib_pistonball.py

### ISSUE THREAD

**Issue by nubonics** [Farama-Foundation/PettingZoo#555]
When specifying a checkpoint_path, it is not able to load params.pkl as I have never ran it before.

Also, there is no default config, so I cannot run this tutorial. [removing the loading of the params.pkl file]
How to train?

**Comment by benblack769** [comment]
The idea is that you can run rllib_pistonball.py first to train the model, then you can use render_rllib_pistonball.py to examine the results of training. We don't include pretrained models in this repo right now.

**Comment by nubonics** [comment]
ah okay, yeah i was kind of oblivious to this before, kinda forgot to close.

Thank you!
