### ISSUE TITLE
Add is_parallelizable as standard metadata argument and add warning to aec->parallel api conversion

### ISSUE THREAD

**Issue by jkterry1** [Farama-Foundation/PettingZoo#560]
The to_parallel wrapper makes a number of assumptions of the environment which cannot be checked. For example, there is no real difference between the hanabi environment, which is turn based (thus the to_parallel wrapper should not be applied) and the pursuit environment, which is not turn based, and can be parallelized.

The intended solution is to add a key in metadata `'is_parallelizable'` (which defaults to false, if not in the metadata). The from_parallel wrapper would add this key to the metadata, and the to_parallel wrapper would check if it is true, and if not, the fail.

**Comment by benblack769** [comment]
In #582, I made this an error, rather than a warning. People can very easily hack around the error if it is a problem.

**Comment by elbamos** [comment]
@jkterry1 can you clarify what needs to be done here?

**Comment by jkterry1** [comment]
So apparently Ben just kinda went and did this himself without me knowing he was going to..?

In the mean time, could you work on getting the render test PR into a state it could be merged?

**Comment by benblack769** [comment]
@jkterry1 I got my render test PR in a mergable state as well.
