### ISSUE TITLE
Training codes

### ISSUE THREAD

**Issue by YimengZhang94** [Farama-Foundation/PettingZoo#562]
It seems there are only codes for environments. Where I can find the training codes using Reinforcement Learning for some basic/classic games? Thanks in advance.

**Comment by zhou163** [comment]
This is the only training example
[https://github.com/Farama-Foundation/PettingZoo/blob/master/tutorials/13_lines.py](url)

**Comment by YimengZhang94** [comment]
> This is the only training example [https://github.com/Farama-Foundation/PettingZoo/blob/master/tutorials/13_lines.py](url)

Ok, thanks

**Comment by YimengZhang94** [comment]
> > This is the only training example [https://github.com/Farama-Foundation/PettingZoo/blob/master/tutorials/13_lines.py](url)
> 
> Ok, thanks

Do you know any other projects that include both environment and training in MARL?

**Comment by benblack769** [comment]
Sure, there are many projects which have training code and environment code, either in the same repo or in related repos: RLCard, OpenSpiel, MAgent (the original repo), SMAC/pymarl, the open source [MuZero](https://github.com/werner-duvaud/muzero-general) implementation, MPE/MADDPG, ML Agents has some example environments and many more.

The long term goal of pettingzoo is to offer a unified way of all these projects to easily port their training code from one project to another, but we are not quite there yet.

**Comment by YimengZhang94** [comment]
> Sure, there are many projects which have training code and environment code, either in the same repo or in related repos: RLCard, OpenSpiel, MAgent (the original repo), SMAC/pymarl, the open source [MuZero](https://github.com/werner-duvaud/muzero-general) implementation, MPE/MADDPG, ML Agents has some example environments and many more.
> 
> The long term goal of pettingzoo is to offer a unified way of all these projects to easily port their training code from one project to another, but we are not quite there yet.

Thanks a lot for your reply. It's very helpful! Hope pettingzoo reaches your aim.
