### ISSUE TITLE
tennis_v2 non zero-sum 

### ISSUE THREAD

**Issue by quantumiracle** [Farama-Foundation/PettingZoo#564]
Hi, 
I found that the environment tennis_v2 in Atari is not a zero-sum game, and the description in the doc `Serves are timed: If the player does not serve within 3 seconds of receiving the ball, they receive -1 points, and the timer resets. This prevents one player from indefinitely stalling the game.` explains that. Is there any possible way to make it zero-sum without this -1 penalty?

Thanks

**Comment by benblack769** [comment]
There isn't an option to allow this, no. When it was decided that this was a good way to handle this problem, the c++ code in the multi-agent ALE repo was changed to give this penalty.

You can probably detect this with custom python code though. When one player gets a -1 reward, and the other gets 0 reward, then you know that this penalty has taken effect, and you can reverse it, giving both 0 reward.

**Comment by quantumiracle** [comment]
Right, I just did it, so I closed this issue. Probably also as a remind to people that this game is not actually zero-sum.

**Comment by benblack769** [comment]
Yeah, its important to remember that. I think I can add something to this effect in the docs to make it very clear.
