### ISSUE TITLE
Questions/concerns about multiwalker

### ISSUE THREAD

**Issue by jkterry1** [Farama-Foundation/PettingZoo#566]
1) The documentation for the reward in multiwalker in the website needs to be edited, and possibly code needs to be fixed. It currently reads:

"A positive reward is awarded to each walker, which is the change in the package distance summed with 130 times the change in the walker’s position. By default, the environment is done if any walker or the package falls. A walker is given a reward of -100 when they fail the game by either condition. If the walker falls, they are penalized an additional -10."

-What is the "either" failing condition mentioned?
-Why 130x? Is that normalizing reward to some predetermined value, and if so what? (and shouldn't that be specified instead of 130x anyways?)
-My understanding was that all walkers get -100 if the package is dropped and individuals get -10 if they kneel. Is that the case? If so its not specified
-Later on in the description a "global reward" argument that doesn't exist is mentioned?

2) Environment behavior when walkers jump off the cliff is not described, and we've had issues where people have learned a good enough policy that this is attainable.

3) While maintenance is ongoing, please pull out local ratio the way Ariel did it in pursuit.

**Comment by jkterry1** [comment]
4) This gif gets an average total reward of 82.25

![trial_208_82 25](https://user-images.githubusercontent.com/19422700/144691756-9496c857-e802-4e4f-89ac-3c48b2d894c1.gif)

While this gets an average total reward of 75.9
![trial_199_75 90](https://user-images.githubusercontent.com/19422700/144691771-7bf585b9-02a7-4000-8849-2f76b436cf1c.gif)

However, it would appear that in the lower reward gif the bots progress much further? Am I going crazy here?

5) Am I correct in my understanding that an optimal policy would look like the agents eventually sitting still clustered at the far right edge of the environment without dropping the package?

**Comment by jkterry1** [comment]
By purely visual inspection, this rollout (reward of 83.42) looks substantially better than all the others? 

![trial_178_83 42](https://user-images.githubusercontent.com/19422700/144691981-9ae85e04-339b-481c-a731-91518c23a067.gif)

**Comment by jkterry1** [comment]
Is the intended maximum possible per agent reward 100 and that's where the normalization comes from?

**Comment by benblack769** [comment]
The reward is mainly based on how far the package goes. I think thats why in all these gifs, the package seems to get propelled forwards.

**Comment by jkterry1** [comment]
The documentation does not say this?

**Comment by jkterry1** [comment]
Closed in favor of #595
