### ISSUE TITLE
Ask a question about the pistonball

### ISSUE THREAD

**Issue by zhouweiqing-star** [Farama-Foundation/PettingZoo#567]
Hello, I'm a novice. I'm very interested in this pettingzoo. In the process of studying it, I now encounter a problem, that is, I don't know how to find the actual position of the piston ball. I hope I can get your reply or the reply of others who can help me

**Comment by benblack769** [comment]
Although its not a standard thing to do for a reinforcement learning problem like this, you should be able to get the position of the center of the ball in pixels with 

```
env.unwrapped.ball.position
````

You can see some simple calculations that use this position here: https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/butterfly/pistonball/pistonball.py#L411

**Comment by zhouweiqing-star** [comment]
> 
Thank you very much for your reply, your suggestion is very effective, especially thank you!

**Comment by zhouweiqing-star** [comment]
> 尽管对于像这样的强化学习问题来说这不是标准的做法，但您应该能够以像素为单位获得球中心的位置
> 
> ```
> env.unwrapped.ball.position
> ```
> 
> 您可以在此处查看使用此位置的一些简单计算：[https](https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/butterfly/pistonball/pistonball.py#L411) : [//github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/butterfly/pistonball/pistonball.py#L411](https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/butterfly/pistonball/pistonball.py#L411)

Thank you very much for your reply, your suggestion is very effective, especially thank you!
