### ISSUE TITLE
Examples of training on the four player team game environments of PettingZoo ? 

### ISSUE THREAD

**Issue by ashutoshs25** [Farama-Foundation/PettingZoo#568]
While learning about multi agent RL, I have mostly come across algorithms which work well for fully cooperative environments, e.g., parameter sharing (https://arxiv.org/abs/2005.13625), QMIX, MADDPG e.t.c. I have also seen and worked on some tutorials / examples available online on using parameter sharing for training a single RL agent on fully cooperative tasks (e.g. this tutorial on training the PettingZoo pistonball env using parameter sharing in RLLib : https://towardsdatascience.com/using-pettingzoo-with-rllib-for-multi-agent-deep-reinforcement-learning-5ff47c677abd)

Since PettingZoo also provides many environments consisting of 4 player games like Quadrapong and Foozpong, I was curious if there are any similar examples or tutorials available for multi agent learning in those settings which I assume are more of a mixed cooperative-competitive type rather than being fully cooperative. Can algorithms like parameter sharing or QMIX work well in these settings and if yes, how to do so ?  If not, then I would appreciate if I could get some pointers to other algorithms which work well in such settings.

**Comment by benblack769** [comment]
One simple method for a team game is to independently train two seperate cooperative methods for each team. In rllib, that means you might just have a policy choice function that directes some of the agents to one policy and the others to another. In a custom implementation, you can send actions of each team to differnet learners. We don't have any examples of this avaliable right now. However, other people have done similar things in the past, for example, you can see how the original MAgent project did this https://github.com/geek-ai/MAgent/blob/master/examples/train_battle.py#L67.

Note that while this independent learning strategy is simple, it has the same convergence problems as independent learning for regular zero sum games. So some league training on top of this strategy might be useful. You can see the openai 5 project for a successful example of this: https://openai.com/five/

**Comment by ashutoshs25** [comment]
Thanks for the reply.

**Comment by ashutoshs25** [comment]
Hi again @benblack769 ,  this might be a silly question but I have not been able to figure out which agents belong to the same team in the Petting Zoo 2 vs 2 team game envs e.g. [Foozpong](https://www.pettingzoo.ml/atari/foozpong). While there are four agents with ids `first_0`,  `second_0`, `third_0`, `fourth_0`, it is not clear from the description on the website, which of these agents are on the same team ?

**Comment by benblack769** [comment]
Yeah, this should be included in the documentation. While that is being fixed, you can refer to the source code: https://github.com/Farama-Foundation/Multi-Agent-ALE/blob/master/src/games/supported/Pong.cpp#L71

Looks like first_0 and third_0 are on a team,a nd second_0 and fourth_0 are on a team, because they share the reward.
