### ISSUE TITLE
[Bug Report] Small bug in cooperative pong

### ISSUE THREAD

**Issue by jkterry1** [Farama-Foundation/PettingZoo#572]
I managed to get a reward of 100.1, while this should not be possible (it should cap at 100). I assume this is due to some sort of off by one/indexing error or something. This does not appear to be a required fix for my MCMES work.

**Comment by jkterry1** [comment]
it's 100.001 not 100.1

**Comment by eczy** [comment]
@jkterry1 Can you please explain how I might be able to reproduce this bug? Is this the reward for a single action or the cumulative reward (e.g. the `score` attribute of the `CooperativePong` environment)?

**Comment by elliottower** [comment]
Closed as this is not reproducible
