### ISSUE TITLE
Notes regarding from_parallel and other conversions

### ISSUE THREAD

**Issue by jkterry1** [Farama-Foundation/PettingZoo#574]
Right now, pettingzoo has tools like:

```
from pettingzoo.utils.conversions import from_parallel
env = from_parallel(par_env)
```

from_parallel should be given a better name, e.g. parallel2aec, the names of conversions should be revisited, and these should be put into pettingzoo.wrappers when that merge happens

**Comment by benblack769** [comment]
Resolved by #604
