### ISSUE TITLE
Move seed into an argument in reset like Gym will in the next release

### ISSUE THREAD

**Issue by jkterry1** [Farama-Foundation/PettingZoo#581]

**Comment by benblack769** [comment]
@jkterry1 Do you have a plan to move gym-ale to this new reset API? I don't see it here: https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/gym/envs/atari/environment.py#L231

**Comment by jkterry1** [comment]
Jesse has to update Atari environments to this himself and hasn't. I'm currently trying to resolve the situation.
