### ISSUE TITLE
How to train magent by stable_baselines3?

### ISSUE THREAD

**Issue by loveisacat** [Farama-Foundation/PettingZoo#587]
Stable_baselines3 can only train the env of "gym"?  Or how to convert the magent-type env to gym-type env that can be trained by stable_baselines3?

**Comment by benblack769** [comment]
MAgent is a very tricky environment to train with SB3. You can try to use use supersuit's `supersuit.pettingzoo_env_to_vec_env_v1` to convert a pettingzoo parallel environment to a Sb3 vector environment. However, since this is a competitive environment, it might or might not work, due to the challenges of self-play in competitive environments.

**Comment by benblack769** [comment]
Note that no one I am aware of has tried to use Sb3 to train magent. Its observation is symmetric enough that self-play might be efficient. Its also worth noting that to reproduce the original results, you should train with `minimap_mode`, which gives each agent access to a global view of the map.

**Comment by loveisacat** [comment]
> Note that no one I am aware of has tried to use Sb3 to train magent. Its observation is symmetric enough that self-play might be efficient. Its also worth noting that to reproduce the original results, you should train with `minimap_mode`, which gives each agent access to a global view of the map.

Thanks for your reply. If I want to train many regular RL algorithms like PPO, A3C in magent. Which RL training tool is recommended except Sb3?  Especially the tools developed based on PyTorch, which do you recommend？

**Comment by loveisacat** [comment]
> Note that no one I am aware of has tried to use Sb3 to train magent. Its observation is symmetric enough that self-play might be efficient. Its also worth noting that to reproduce the original results, you should train with `minimap_mode`, which gives each agent access to a global view of the map.

Thanks for your reply. If I want to train many regular RL algorithms like PPO, A3C in magent. Which RL training tool is recommended except Sb3?  Especially the tools developed based on PyTorch, which do you recommend？

**Comment by jkterry1** [comment]
Hey, RLlib is probably what you're looking for
