### ISSUE TITLE
Github action for cutting new releases

### ISSUE THREAD

**Issue by jkterry1** [Farama-Foundation/PettingZoo#591]
GitHub actions has a feature where you can automatically cut releases for libraries just by creating a new release on github. We should really do this for both pettingzoo and supersuit (and merge master into the website branch during the same action if thats possible). This would keep me from annoying Ben or having to go and look up the instructions for release every single time.

**Comment by eczy** [comment]
@jkterry1 if you can please elaborate on what exactly is needed here (and point me toward the current release instructions), I can take a look at it.

**Comment by benblack769** [comment]
@jkterry1 I'm not sure what benefit this will have. Releasing literally takes less than 1 minute, if you know how to do it. The vast majority of the effort is in checking the version bumps, writing the release notes, etc.

**Comment by jkterry1** [comment]
@eczy See this for an example: https://github.com/vwxyzjn/gym-microrts/blob/master/.github/workflows/pypi.yml

**Comment by jkterry1** [comment]
This should be done for supersuit too
