### ISSUE TITLE
different observation space shape after env.step()

### ISSUE THREAD

**Issue by xiaominy** [Farama-Foundation/PettingZoo#593]
hello, i got some problems when i using pettingzoo.
when i use  env.observation_spaces["first_0"].shape to get agent's observation_space shape, the result is 128, but "observation" in the output of env.step(actions) shows 512. I wonder if you know why?

env = pong_v2.parallel_env(num_players=2, obs_type='ram', max_cycles=100000)
env = supersuit.max_observation_v0(env, 2)
env = supersuit.sticky_actions_v0(env, repeat_action_probability=0.25)
env = supersuit.frame_skip_v0(env, 4)
env = supersuit.frame_stack_v1(env, 4)

env.reset()
print(env)  #pong_v2
print(env.agents)
print(env.observation_spaces["first_0"].shape)  #(128,)
print(env.action_spaces) #{'first_0': Discrete(18), 'second_0': Discrete(18)}

actions = {agent: 1 for agent in env.agents}
observation, reward, done, info = env.step(actions)
print(observation)
obs = [observation[i].shape for i in observation.keys()]  #[(512,), (512,)]

**Comment by benblack769** [comment]
Hi, I belive this is a bug found in old versions of pettingzoo and supersuit that is now fixed. Please use the latest versions of both packages.

**Comment by xiaominy** [comment]
Thanks! The problem was solved through your advice!
