### ISSUE TITLE
Missing "Wrapper" page from main website + Colab Atari ROMs

### ISSUE THREAD

**Issue by Phoenix-surgere** [Farama-Foundation/PettingZoo#606]
Hello, I am new to using PettingZoo and I have two issues:

1) I do not understand why the "Wrappers" page from the website always gets a 404 Error. Is it missing intentionally or is something bad on my end? The rest of the website works and I find it curious that an entire section is nowhere to be found.

2) I cannot for the life of me get the Atari ROMs to work in Colab. I ran the command from AutoROMS, I see the .bin files in my collab, I can even run them via the original multi-agent ale library but for some reason every time I try to instantiate the space invaders environment (for example) I get the 

```
OSError: rom space_invaders is not installed. Please install roms using AutoROM tool (https://github.com/Farama-Foundation/AutoROM) or specify and double-check the path to your Atari rom using the `rom_path` argument.
```

error. Is there anything that can be done about either of these issues?

**Comment by benblack769** [comment]
Wrappers appears to be a typo in the link. The correct link is: https://www.pettingzoo.ml/wrappers#environment-vectorization
The link the website directs you to is https://www.pettingzoo.ml/Wrappers#environment-vectorization

**Comment by benblack769** [comment]
I was able to get AutoROM working by running:


```
! pip install autorom
```


```
! AutoROM -y
```

```
from pettingzoo.atari import space_invaders_v1
space_invaders_v1.env()
```

**Comment by Phoenix-surgere** [comment]
Many thanks, ben, I just tried both the correct link and the code you suggested and finally got it to work! I was missing the second command you pasted and apparently, something went wrong without it, since I spent several hours trying out stuff from the Auto-Rom website to no avail. I also had no idea that the link was just a URL typo, would have never found that out myself. Many thanks!
