### ISSUE TITLE
Need some clarifications on API

### ISSUE THREAD

**Issue by mvadrev** [Farama-Foundation/PettingZoo#624]
Hey Guys,

First of all thank you so much for creating the PettingZoo MARL library. I am trying to implement 2 robotic arms working in cooperation with a joint state in a parallel environment. I want to use stablebaselines3 PPO to achieve this. I have tried reading the documentation but I have some questions about the flow for a custom environment. Can you please help as some of the things in the documentation are not making sense.  

1. Most of the examples quoted int he tutorials import pistorballv4 or v6. But this is no longer the newest version I guess. So, there seem to be some discrepancies. For example if you see the page for custom parallel environment: https://www.pettingzoo.ml/api#parallel-api

It says use the follwoign example code: 

`
parallel_env = pistonball_v1.parallel_env()
observations = parallel_env.reset()
max_cycles = 500
for step in range(max_cycles):
    actions = {agent: policy(observations[agent], agent) for agent in parallel_env.agents}
    observations, rewards, dones, infos = parallel_env.step(actions)
`

But what is policy() here? Is it a pettingZoo function or something else?  What is the import? Is this a method in the class?

2.  What is env.last()? Seems to be again related to the old pistonball source but in the new pistonball.py file I cannot find any method or import called last(). 

3. Here is my code for my custom class. Can you please guide me if I am going about this right?

`
#including colab link so you can quickly run and debug it
https://colab.research.google.com/drive/1J1seADLVIF0FWD5wfTq0Y4niSHgIPsAI#scrollTo=Rf7myNS5XKgR
`

4. Can you help me formalize the correct flow?

**Comment by jkterry1** [comment]
@mvadrev please take a look at https://towardsdatascience.com/multi-agent-deep-reinforcement-learning-in-15-lines-of-code-using-pettingzoo-e0b963c0820b#c7cb

**Comment by mvadrev** [comment]
Hi,

My question is with building a custom parallel environment. So, I want to use stablebaselines3 with AEC environment. 

1. If I apply PPO on my custom environment in a parallels environment where all agents step simultaneously, i understand the step function is called at every time step. Is the policy calculated one agent at a time like how i wrote my code below? Does my custom environment look right?
`
from pettingzoo.utils import agent_selector

# Arm 1 starts making batteries only when there are at the least 5 components of each of the 3
# Arm 2 has to decide which current part to pick from the converyer belt as per the inventory levels of the bins

class MARL(ParallelEnv):
  metadata = {'render.modes': ['human'], "name": "rps_v2"}

  def __init__(self):
    self.possible_agents = ["player_" + str(r) for r in range(2)]

    self.agent_name_mapping = dict(zip(self.possible_agents, list(range(len(self.possible_agents)))))

    
    #assign mapping to self.sgent
    self.agents = self.possible_agents[:]
    self._agent_selector = agent_selector(self.agents)
    self.agent_selection = self._agent_selector.reset()

    # Arm 1 state 
    self.busy_arm =1
    self.busy_table = 1
    self.layer1 = 0
    self.layer2 = 2
    self.layer3 = 3
    self.arm_position = 3
    self.dones =  dict(zip(self.agents, [False for _ in self.agents]))
    print(self.dones)

    # Arm 2 state 
    self.busy_arm2 = 1 
    self.arm_position2 = 3 

    #Conveyer belt state 
    self.parts_list = [0,0,0,1,2,2,1,0,1]
    self.current_part = 0 

    self.cathode_count = 0 
    self.anode_count = 0 
    self.seperator_count = 0 


  def process_reward(self, agent_id, action):
    #Process reward for agent 1
    if(agent_id == 0):
      pass

    else:
      pass 
      #Process reward for agent 2

  def step(self, action):

    if self.dones[self.agent_selection]:
            return self._was_done_step(action)
    else:        
      self._agent_selector = agent_selector(self.agents)
      agent = self.agent_selection

      if(action == 3):
        #do something i.e
        return observations, rewards, dones, infos

      if(action == 0):
        #do something else 
        return observations, rewards, dones, infos
           
      # Do something here i.e get next state and process reward

      # AFter finishishing set agent to next agent
      self.agent_selection = self._agent_selector.next()

      



  def reset(self):
    pass
`

**Comment by mvadrev** [comment]
Here is a more updated custom environment with two robots. I created one separate  processTransistion function for the 2 robots. 

I have another question. If I for example apply PPO, will the Petting Zoo automatically update the policy at each timestep individually for each agent? or do I have to define this manually?

Currently, I am using the agent selector method to select an agent at each time step and then after my transition & reward function, I am using the agent_selector.next() function to get the next agent as seen below. Is this the correct way of doing parallel environment where all agents step simultaneously?


`
from pettingzoo.utils import agent_selector
from gym import spaces
import numpy as np 
import pandas as pd

# Arm 1 starts making batteries only when there are at the least 5 components of each of the 3
# Arm 2 has to decide which current part to pick from the converyer belt as per the inventory levels of the bins

class MARL(ParallelEnv):
  metadata = {'render.modes': ['human'], "name": "rps_v2"}

  def __init__(self):
    self.possible_agents = ["player_" + str(r) for r in range(2)]
    self.agent_name_mapping = dict(zip(self.possible_agents, list(range(len(self.possible_agents)))))
    # Define Action space
    self.action_space = spaces.Discrete(7)
    # Episode lenght - When the game should end 
    self.episodeLength = 20
    # Define observation space - Need to change this
    self.observation_space = spaces.Box(0, 6, shape=(6,), dtype=np.uint8)
    # Load necessary files 
    self.done = False
    self.reward_csv = pd.read_csv("./reward.csv")


    #assign mapping to self.sgent
    self.agents = self.possible_agents[:]
    self._agent_selector = agent_selector(self.agents)
    self.agent_selection = self._agent_selector.reset()

    # Arm 1 state 
    self.busy_arm =1
    self.busy_table = 1
    self.layer1 = 0
    self.layer2 = 2
    self.layer3 = 3
    self.arm_position = 3
    self.dones =  dict(zip(self.agents, [False for _ in self.agents]))
    print(self.dones)

    # Arm 2 state 
    self.busy_arm2 = 1 
    self.arm_position2 = 3 

    #Conveyer belt state 
    self.parts_list = [0,0,0,1,2,2,1,0,1]
    self.current_part = 0 

    self.cathode_count = 0 
    self.anode_count = 0 
    self.seperator_count = 0 

    # Current state 
    self.current_state = [self.busy_arm, self.busy_table, self.layer1, self.layer2, self.layer3, self.arm_position, self.busy_arm2, self.arm_position2, self.cathode_count, self.anode_count, self.seperator_count]
    print("The state space is", len(self.current_state) + " long")


  def process_currentStateRobotOne(self,action):
    #Make a copy of current state before manipulatign it
    current_state = self.current_state[:]
    # print("Processing current state...")
    #corresponding to E; W; N; S;
    if(action < 4):
      self.arm_position = action
    # Corresponding to Pick; Place actions
    else:
      # If action is pick
      if(action == 4 ):
        if(self.busy_arm == 3):
          # print("Arm is not holding anything so picking up", action)
          self.busy_arm = self.arm_position
      #Action is place
      if(action == 5):
        if(self.busy_arm != 3):
          # print("Arm is busy hence placing part:", self.busy_arm)
          if(self.layer1 == 3):
            # print("Layer1 is empty so inserting..", action)
            self.layer1 = self.busy_arm
            self.busy_arm = 3
            self.busy_table = 1
          elif(self.layer1 !=3 & self.layer2 == 3):
            self.layer2 = self.busy_arm
            self.busy_arm = 3
            self.busy_table = 1
          elif(self.layer1 !=3 & self.layer2 !=3  & self.layer2 == 3):
            self.layer3 = self.busy_arm
            self.busy_arm = 3
            self.busy_table = 1
          else:
            print("The layer is already placed.")
      # Actions beyond 5 (Added on 2/13/2022) - Only Wait Action is left 
      if(action == 6):
        pass


    #Get next state from the updated self.current_state 
    next_state = [self.busy_arm, self.busy_table, self.layer1, self.layer2, self.layer3, self.arm_position, self.busy_arm2, 
    self.arm_position2, self.cathode_count, self.anode_count, self.seperator_count]
    # print("The next state is", next_state)
    state = np.array(next_state, dtype=np.float32)
    #Get reward from next state
    reward = self.process_reward(current_state, action)
    # print("The reward, current_state and action are: ", reward, self.current_state, action)
    self.current_state = next_state
    done = self.done
    return state, reward, done, {}

  def process_currentStateRobotOne(self,action):
    #Make a copy of current state before manipulatign it
    current_state = self.current_state[:]
    # Actions = {0, 1, 2, 3, 4}
    if(action < 2):
      # Directional actions are less than 2 
      self.arm_position2 = action 
    if(action == 2):
      # If action = 2 or Pick
      pass
    if(action > 2):
      # If action is place
      if(action == 3):
        # Check which part the arm is holding and appropriately add it to inventory count 
        # If part is cathode
        if(self.busy_arm2 == 0):
          self.cathode_count += 1
        #if part is cathode
        if(self.busy_arm2 == 1):
          self.anode_count += 1
        #if part is seperator 
        if(self.busy_arm2 == 2):
          self.seperator_count += 1
        # Check arm is busy but trying to to the wring things
        if(self.busy_arm2 != 3):
          # Case 1 : If arm is trying to pick when already busy
          if(action == 2):
            pass 

      # if action is wait
      if(action == 4):
       pass
       #Dont do anything 
      
      # Update state
      next_state = [self.busy_arm, self.busy_table, self.layer1, self.layer2, self.layer3, self.arm_position, self.busy_arm2, self.arm_position2, self.cathode_count, self.anode_count, self.seperator_count]
      state = np.array(next_state, dtype=np.float32)
      #Get reward from next state
      reward = self.process_reward(current_state, action)
      # print("The reward, current_state and action are: ", reward, self.current_state, action)
      self.current_state = next_state
      done = self.done
      return state, reward, done, {}
    


  def process_reward(self, agent_id, action):
    #Process reward for agent 1
    if(agent_id == 0):
      pass

    else:
      pass 
      #Process reward for agent 2

  def step(self, action):

    if self.dones[self.agent_selection]:
            return self._was_done_step(action)
    else:        
      self._agent_selector = agent_selector(self.agents)
      agent = self.agent_selection

      if(agent == 0):
        #do something i.e
        self.process_currentStateRobotOne(action)

      if(agent == 1):
        self.process_currentStateRobotTwo(action)
           
      # Do something here i.e get next state and process reward

      # AFter finishishing set agent to next agent
      self.agent_selection = self._agent_selector.next()

      
  def reset(self):
    self.episodeLength = 0

    self.busy_arm =3
    self.busy_table = 0
    self.layer1 = 3
    self.layer2 = 3
    self.layer3 = 3
    self.arm_position = 0
    # Arm 2 state 
    self.busy_arm2 = 1 
    self.arm_position2 = 3 
    #Conveyer belt state 
    # self.parts_list = [0,0,0,1,2,2,1,0,1]
    self.current_part = 0 
    self.cathode_count = 0 
    self.anode_count = 0 
    self.seperator_count = 0 

    self.current_state = [self.busy_arm, self.busy_table, self.layer1, self.layer2, self.layer3, self.arm_position]
    self.done = False
    

`

**Comment by benblack769** [comment]
1. Yes, you will need to figure out how you wish to update your policy as well. 
2. You can calculate the policy one agent at a time, or, if your environment allows, you can batch together all the agents with something like `np.concatenate([observations[agent] for agent in env.agents])`

**Comment by jkterry1** [comment]
Hey, I'm going to close this due to inactivity, please let us know if you need anything else from us
