### ISSUE TITLE
[Proposal] Blacken the codebase

### ISSUE THREAD

**Issue by RedTachyon** [Farama-Foundation/PettingZoo#628]
So I know there's a `check_style.sh` but it doesn't seem to actually be used? In the CI flake8 has a bunch of complaints even on current master and those are then ignored. But if the imports are incorrectly ordered, the CI will be stopped. 

I suggest scrapping all of that and going with "In black we trust", similarly to gym - blacken the codebase, and then for subsequent code modifications all you need to pay attention to is to run `black .` before pushing. Or after, more often than not.

**Comment by benblack769** [comment]
This was actually done previously https://github.com/Farama-Foundation/PettingZoo/pull/455 but then I couldn't read the codebase anymore, so I reset the changes. 100% of the blame lies on me.

Since I'm not as active on the project anymore, this might be good to revist.

**Comment by benblack769** [comment]
some more discussion https://github.com/Farama-Foundation/PettingZoo/pull/459

**Comment by benblack769** [comment]
Got linting working back on https://github.com/Farama-Foundation/PettingZoo/pull/631

**Comment by benblack769** [comment]
To be clear, I am fine with individual fines being blackened for individual projects (the recent KAZ or waterworld efforts, for example, it is whole codebase blacking that makes my brain hurt.
