### ISSUE TITLE
Parallel API question

### ISSUE THREAD

**Issue by openenergylab** [Farama-Foundation/PettingZoo#646]
I have an environment with multiple different robots that all step at the same time (i.e they use action wait if they have to wait. But all agents perform some action at each time step).

I have one robot that makes sandwiches and the other one picks up ingredients from a conveyer belt.

My question is is parallel API correct to make this environment with or is parallel API just a way to parallelize the same robot to learn faster?

Because I seem to have done everything correct but my code does not run
`
# reward csv
https://drive.google.com/file/d/1OrcTUvt4yCNMuOfKqwrpJnE5TtbA543x/view?usp=sharing
# code
https://colab.research.google.com/drive/1hLcf2Oj3yUqCU-gpAMQMD6SE9y_aijcH#scrollTo=Od29FUZw1iIK
`

**Comment by benblack769** [comment]
Sorry about the late reply, yes, the parallel API should be a correct choice, it only really means that the agent step at the same time.

**Comment by mvadrev** [comment]
Let me do one thing. I will break my code down into pseudocode and paste here so it is easy for you to quickly look at it and tell me where I am creating a bug. Thank you for your response.

**Comment by mvadrev** [comment]
Well not yet here is my pseudo code. But, it still throws a dimensionality error. I have the highly reduced pseudo code below. I did not mention the reset method. But I confirm it it there. Here is the full code:

https://colab.research.google.com/drive/1g57BeUbkPiTdMIIVUqxlx4dZZ8XDe-JB#scrollTo=0XzwOHp9q5To

After running the class as mentioned below, I want to train using stablebaselines. But that is the place where the error is coming. Can you plz help?


`
env2 = env()
# env.process_reward(1,0,5)
print(isinstance(env2, ParallelEnv))
env2= ss.pettingzoo_env_to_vec_env_v1(env2) <------------ error coming here
env2 = ss.concat_vec_envs_v1(env2, 8, base_class='stable_baselines3') <------------ error coming here


`

class(ParallelEnv):
self.s1 = 0
self.s2 = 0
self.s3 = 0
self.currentstate=[s1, s2, s3]
def action_space(self, agent):
      return spaces.Discrete(7)

  def observation_space(self, agent):
    return spaces.Box(0, 12, shape=(12,), dtype=np.uint8)

  def process_currentStateRobotOne(self,action):
                    this function processes the next state and updates eveything directly into s1 s2 s3
 def process_currentStateRobotTwo(self,action):
                      this function processes the next state and updates eveything directly into s1 s2 s3

 def process_reward(self, current_state, agent_id, action):
              returns reward based on agent we passed in
def step(self,action):
if self.dones[self.agent_selection]:
            return self._was_done_step(action)
    else:        
      self._agent_selector = agent_selector(self.agents)
      agent = self.agent_selection
      # Process next state and reward for agent 0
      if(agent == 0):
        #do something i.e
        self.process_currentStateRobotOne(action)
        state1, reward1 = self.process_reward(state ,0, action) 

      # Process next state and reward for agent 1
      if(agent == 1):
        self.process_currentStateRobotTwo(action)
        state2, reward2 = self.process_currentStateRobotTwo(state, 1, action)

        
           
      # AFter finishishing set agent to next agent
      self.agent_selection = self._agent_selector.next()

      # Obtaine observations (2/19/2022)
      observations = {self.agents[0]: action[0], self.agents[1]: action[1] }
      # obtanin reward (2/19/2022)
      rewards = {}
      rewards[self.agents[0]] = reward1
      rewards[self.agents[1]] = reward2
      # rewards[self.agents[0]], rewards[self.agents[1]] = REWARD_MAP[(actions[self.agents[0]], actions[self.agents[1]])]
      infos = {agent: {} for agent in self.agents}
    return observations, rewards, self.dones, infos

**Comment by jjshoots** [comment]
It seems that the problem is with pandas and that it can't find the file `reward.csv`? It doesn't seem to be a pettingzoo problem, but seems to be that the jupyter notebook can't find the file you're specifying.

**Comment by mvadrev** [comment]
I have attached reward.csv above man. Here it is for your testing.

https://drive.google.com/file/d/1OrcTUvt4yCNMuOfKqwrpJnE5TtbA543x/view?usp=sharing

 I feel like 97% of the implementation is done. If you can help me figure out the error, I will be happy to write a detailed tutorial on how to do custom environments wth pettingzoo for your website

**Comment by jjshoots** [comment]
I'm sorry, but we're currently not entertaining debugging people's usage of PettingZoo that has issues unrelated to the PettingZoo library itself.

**Comment by mvadrev** [comment]
Thank you! I will post on discord
