### ISSUE TITLE
Stable-Baseline3 Compatibility with Gym

### ISSUE THREAD

**Issue by marctheshark3** [Farama-Foundation/PettingZoo#647]
When I try to run your example code with stable-baseline I get a problem with a mismatch of gym version. PettingZoo wants the latest and stable baseline 3 wants a version between 0.17 and 0.2.

**Comment by marctheshark3** [comment]
https://towardsdatascience.com/multi-agent-deep-reinforcement-learning-in-15-lines-of-code-using-pettingzoo-e0b963c0820b this article

**Comment by jkterry1** [comment]
There's a PR to SB3 to support the newest version of Gym. In the mean time if you just overwrite the SB3 dependency with the newest Gym version it will work just fine.

**Comment by marctheshark3** [comment]
Perfect thank you!!
