### ISSUE TITLE
each agent has a different reward function

### ISSUE THREAD

**Issue by nollied** [Farama-Foundation/PettingZoo#650]
is it possible for agents to have different reward functions?

**Comment by benblack769** [comment]
Yes, you can see the documentation for the simple_adversary  environment https://www.pettingzoo.ml/mpe/simple_adversary as a very simple example of a env where the two agents have very different reward functions.

**Comment by jkterry1** [comment]
Hey, I'm going to close this as the question has been answered, please let us know if you need anything else from us
