### ISSUE TITLE
Error with agents being done at different times

### ISSUE THREAD

**Issue by LaurenYTaylor** [Farama-Foundation/PettingZoo#652]
G'day there,

I have run into an issue in an environment where agents are done at different times. It is possible that PettingZoo is not meant to support this, but I was under the impression it was (e.g. for when agents die throughout an episode) - apologies if not. I realised this problem when I made a test version of my environment which would run each agent until it had taken every possible action from its action space (I wanted to make sure the actions were working as intended), then it would be marked as done. Let's say we have 4 agents: two agents with 2 possible actions and the second two agents with 4 possible actions. After two cycles over all the agents, the first two agents are marked as done. On the next cycle, when it is the first "done" agent's turn, I call the following if statement at the beginning of step(), which now evaluates as true:
```
if self.dones[self.agent_selection]:
    self._was_done_step(action)
    return
```
and ``` self.was_done_step(action) ``` is called. This removes the first agent from the environment (```self.dones```, ```self.agents``` etc)., but if there is another "done" agent in the environment (which there is, the second agent with an action space size of 2), it then sets ```self._skip_agent_selection``` to the first agent. Then, it steps the next done agent (the second agent), which calls the above if statement again, deletes the agent from the environment (```self.dones```, ```self.agents``` etc. etc)., and once it's done, it sets the ```self.agent_selection = self._skip_agent_selection```, which (as I said before) is the first agent we first removed from the environment. But because we removed that agent from the environment, when it tried to call ```env.last()``` and return things such as ```self.dones[self.agent_selection]```, you get a ```KeyError``` since that agent has already being removed from the environment. I don't really understand what the point of the ```self._skip_agent_selection``` is at all, I'm clearly doing something wrong because there must be a reason for it. I have written a MWE below to demonstrate the issue. If this is the intended behaviour, I'd really appreciate any help with understanding how I am supposed to be removing agents from the environment. Thank you very much for your help.

Cheers,
Lauren

```
import random
import pettingzoo
from pettingzoo.utils.agent_selector import agent_selector
from gym.spaces import Discrete

class ExampleEnv(pettingzoo.AECEnv):
    def __init__(self, num_agents=5, cutoff=3):
        self.observation_space = {}
        self.action_space = {}
        self.n_agents = num_agents

        for i in range(0, cutoff):
            self.observation_space[i] = Discrete(5)
            self.action_space[i] = Discrete(3)

        for i in range(cutoff, self.n_agents):
            self.observation_space[i] = Discrete(5)
            self.action_space[i] = Discrete(6)

    def reset(self):
        self.remaining_actions = {}
        self.agents = list(range(self.n_agents))
        for i in self.agents:
            self.remaining_actions[i] = list(range(self.action_space[i].n))
        self._agent_selector = agent_selector(self.agents)
        self.agent_selection = self._agent_selector.reset()
        self.rewards = {name: 0 for name in self.agents}
        self._cumulative_rewards = {name: 0 for name in self.agents}
        self.dones = {name: False for name in self.agents}
        self.infos = {name: {} for name in self.agents}
    
    def step(self, action):
        if self.dones[self.agent_selection]:
            self._was_done_step(action)
            return
        self.remaining_actions[self.agent_selection].remove(action)

        self.rewards[self.agent_selection] = 0
        
        if len(self.remaining_actions[self.agent_selection]) == 0:
            self.dones[self.agent_selection] = True
        self.agent_selection = self._agent_selector.next()
        self._accumulate_rewards()

    def observe(self, agent):
        return self.observation_space[agent].sample()

    def render(self, mode='human'):
        pass

    def state(self):
        pass

    def close(self):
        pass

    def observation_space(self, agent):
        return self.observation_spaces[agent]

    def action_space(self, agent):
        return self.action_spaces[agent]


def main():
    env = ExampleEnv()
    episodes = 1
    completed_episodes = 0
    while completed_episodes < episodes:
        env.reset()
        for agent in env.agent_iter():
            print("Agent: ", agent)
            obs, reward, done, _ = env.last()
            if done:
                action = None
            elif isinstance(obs, dict) and 'action_mask' in obs:
                action = random.choice(np.flatnonzero(obs['action_mask']))
            else:
                action = random.choice(env.remaining_actions[agent])
            env.step(action)
        completed_episodes += 1

if __name__ == "__main__":
    main()

```

**Comment by benblack769** [comment]
So the logic behind correctly removing agents is highly unintuitive and very difficult to do correctly, and we generally try to avoid implementing it with the AEC API, most environments just implement the parallel API, and convert it to an AEC environment using the `parallel_to_aec_wrapper` wrapper. An example of this is magent environments https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/magent/battle_v3.py#L29

If this is not an option for you, then you can refer to the parallel_to_aec_wrapper https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/utils/conversions.py#L241 or KAZ https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/butterfly/knights_archers_zombies/knights_archers_zombies.py#L557 for examples of how to remove agents according to the spec.
