### ISSUE TITLE
Training performance metrics

### ISSUE THREAD

**Issue by Axelskool** [Farama-Foundation/PettingZoo#655]
We have a parallel environment and are using stable-baselines3 and pytorch and are wondering how we can get out rewards during training?  Callbacks and Monitor doesn't seem to work for petting-zoo. Is there a way to get this information?

Much grateful for response!

Axel

**Comment by jjshoots** [comment]
Hi @Axelskool, I believe you've asked this in the RL Discord channel and your question was answered right?

**Comment by Axelskool** [comment]
@jjshoots No, I only asked this question here. Is there a way to get the rewards?

Thank you for your reply!

**Comment by jjshoots** [comment]
@benblack769 Care to elaborate?

**Comment by benblack769** [comment]
Likely the solution would be to include something equivalent to the VecMonitor wrapper in SB3, except for pettingzoo environments: https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html?highlight=vecmonitor#vecmonitor

**Comment by benblack769** [comment]
In the short run, you might be able to apply SB3's VecMonitor directly to the vector environment output by the supersuit cat_vec_envs wrapper, although it will give somewhat inaccurate results for epiode lengths and number of episodes, you should be able to correct for the number of episodes, and the rest of the stats should be correct. 

Alternatively, in the long run, someone could create an equivent version of the VecMonitor, specifically for PZ environments.

**Comment by jjshoots** [comment]
@Axelskool, does that answer your question? :)

**Comment by Axelskool** [comment]
Yes thank you very much @benblack769  and @jjshoots . We will be sure to cite petting-zoo in our master thesis if we manage to train our policy and use it! 

Much appreciated!
