### ISSUE TITLE
Potentially fixing pettingzoo env conventions

### ISSUE THREAD

**Issue by jjshoots** [Farama-Foundation/PettingZoo#685]
Excerpt from Ariell:

I think I was supposed to describe my thoughts on the class structure in PZ, but then it fell through the cracks, I see there's some discussions on this now. 

Basically, I think it'd be much better to stick to a more typical class-inheritance model. Basically we'd have two top-level abstract classes `AECEnv`  and `ParallelEnv` as we have now. And then each environment would have a proper name, e.g. `class PursuitParallelEnv(ParallelEnv)` or `class PursuitAECEnv_v4(AECEnv)` (depending on whether we want to put the version in class names or not)

The basic env creation would then be from `pettingzoo.sisl.pursuit_v4 import PursuitParallelEnv` and such. 

To have the same workflow as currently, we could add something like 

```python
def parallel_env(*args, **kwargs):
    return PursuitParallelEnv(*args, **kwargs)

to  pursuit_v4.py  (or define it elsewhere and import it)
```

Tbh my biggest issue is that the code in its current form just seems sloppy, with multiple classes having the same name (so we lose some of the nice python introspection stuff, and things are confusing), not following standard python conventions. At first when I saw code like `pursuit_v4.parallel_env()` I was sure that paralell_env was a function, but it's not. And imo it should be. 

A potentially more tricky thing will be updating the `aec_to_parallel` conversions and the other way around, iirc it has some interactions with supersuit which is also a bunch of mess

**Comment by WillDudley** [comment]
This issue is probably a subset of https://github.com/Farama-Foundation/PettingZoo/issues/803
