### ISSUE TITLE
Run through release test and squash any bugs that can be squashed.

### ISSUE THREAD

**Issue by jjshoots** [Farama-Foundation/PettingZoo#686]

**Comment by virgilt** [comment]
Hi @jjshoots, I'm new to this repo and the world of ML/AI (current student in GT's MSCS program) and want to contribute. Would I be able to take this issue? Also, can you explain what I need to do specifically? Thanks! - Trav

**Comment by jjshoots** [comment]
Hi @virgilt, glad to have you onboard! You're free to take the issue under your wing if you feel like it.

Basically PettingZoo, as it stands, has seen a lot of development through the many release cycles of the libraries that it depends on. As a result of this, we're seeing more and more deprecation warnings, semantics warnings, etc. as time goes on in our tests.

The goal of this 'issue' is to pretty much run `./release_test.sh`, and find any and all such warnings and then solve them within the codebase wherever possible and convenient to do so. Undoubtedly it's impossible to solve all of them, and many of them will require special attention, but the preliminary goal is to at least run through the surfacial level ones and handle those that are easy to solve.

Are you in the [official RL discord group](https://discord.gg/VccSD2Yw) or [PZ/Gym developers group](https://discord.gg/uw9CFTFE) btw? I'd encourage you to join and give me (`@jat`) a PM, and then we can move on from there.  But should you choose not to, we accept just general PRs that address this issue as well, though integration and communication may be a bit delayed.

**Comment by pseudo-rnd-thoughts** [comment]
@jjshoots @virgilt What is the status of this issue?

**Comment by WillDudley** [comment]
@jjshoots Is this issue still relevant?

**Comment by jjshoots** [comment]
AFAIK this is always relevant, @reginald-mclean is on it if I'm not wrong.

**Comment by WillDudley** [comment]
@reginald-mclean Do you have an update?
