### ISSUE TITLE
cannot import name '_dill' from 'pettingzoo.classic'

### ISSUE THREAD

**Issue by huameichen0523** [Farama-Foundation/PettingZoo#707]
I followed the Tic-Tac-Toe tutorial and it worked great. However, I was not able to save Q using dill. The message I obtained was "cannot import name '_dill' from pettingzoo.classic. 
I am using Ubuntu 20.04 with Python 3.9.12 and dill 0.3.5.1.

Any advice is greatly appreciated.

HM

**Comment by jjshoots** [comment]
Hi @huameichen0523, just for context, which tutorial are you referring to (I'm not too well versed in some of them in the docs)?

**Comment by huameichen0523** [comment]
I was following the tutorial from this link: https://www.pettingzoo.ml/tutorials
Tic-Tac-Toe is the second one. 
The specific piece of code is the following:
========================================
from marl_qlearning import *
env = tictactoe_v3.env()
random.seed(123)
fullrun = 0
if fullrun:
    Q, N = marl_q_learning(env, 500_000, alpha = 0.6, gamma = 0.95, \
                           decay = True, render = False)
    with open('cached/Q.pkl', 'wb') as f:
        dill.dump(Q, f)    
else:
    with open('cached/Q.pkl', 'rb') as f:
        Q = dill.load(f)    
=============================================

I was not able to save the trained Q due to the reported error.

Thank you.

**Comment by jjshoots** [comment]
I don't think this is actually a problem with PettingZoo, but rather a problem with the tutorial or code that you're using.

Instead of a star import, could you try perhaps doing something like the below if the function `marl_qlearning` is in a file `marl_qlearning.py`?

```py
from marl_qlearning import marl_qlearning
```

**Comment by huameichen0523** [comment]
In fact in my implementation, I coded marl_q_learning in the main code and no import at all.
The error occurs when "dill.dump(Q,f) " is executed.
Below is the complete code I wrote.

Thank you!
=============================
from pettingzoo.classic import tictactoe_v3
import random
import numpy as np
from collections import defaultdict
import dill
import hashlib
import pickle
import matplotlib.pyplot as plt

def encode_state(observation):
    # encode observation as bytes           
    obs_bytes = str(observation).encode('utf-8')
    # create md5 hash
    m = hashlib.md5(obs_bytes)
    # return hash as hex digest
    state = m.hexdigest()
    return(state)

def make_epsilon_greedy_policy(Q, epsilon, nA):
    def policy_fn(state,action_mask):
        A = action_mask*np.ones(nA, dtype=float) * epsilon / nA
        tmp = np.where(action_mask==1)
        best_action = np.argmax(Q[state][tmp[0]])
        A[tmp[0][best_action]] += (1.0 - epsilon)
        return A # fixed numbers
    return policy_fn


def marl_q_learning(multi_env, num_episodes,alpha,gamma=1.0,
                    eps_start=1.0, eps_decay=.99999,eps_min=0.025):
    
    multi_env.reset()
    Q = {}
    for agent in multi_env.agents:    
        nA = multi_env.action_spaces[agent].n
        Q[agent] = defaultdict(lambda: np.zeros(nA))
    
    epsilon = eps_start

    i_episode = 1    

    prev_state = {'player_1': -1,
                  'player_2': -1}
    prev_action = {'player_1': -1,
                  'player_2': -1}

    # keeps iterating over active agents until num episode break
    while i_episode <= num_episodes:
        if i_episode%10000 == 0:
            print(i_episode)
        policy = {}
        for agent in multi_env.agent_iter():           
            # get observation (state) for current agent:
            observation, reward, done, info = multi_env.last()
            state = encode_state(observation['observation'])
            # perform q-learning with update_Q_value()
            best_next_action = np.argmax(Q[agent][state])    
            td_target = reward + gamma * Q[agent][state][best_next_action]
            td_delta = td_target - Q[agent][prev_state[agent]][prev_action[agent]]
            Q[agent][prev_state[agent]][prev_action[agent]] += alpha * td_delta
            
            # store current state
            prev_state[agent] = state
            
            if not done: 
                # choose action using epsilon_greedy_policy()
                policy[agent] = make_epsilon_greedy_policy(Q[agent], epsilon, multi_env.action_spaces[agent].n) 
                action_probs = policy[agent](state,observation['action_mask'])
                action_probs = action_probs/sum(action_probs)
                action = np.random.choice(np.arange(len(action_probs)), p=action_probs)
                multi_env.step(action)
                # store chosen action
                prev_action[agent] = action 
            else: 
                # agent is done
                multi_env.step(None)
        # reset env and memory
        #multi_env.render()
        multi_env.reset()
        prev_state = {'player_1': -1,
                      'player_2': -1}
        prev_action = {'player_1': -1,
                       'player_2': -1}
        # bump episode
        i_episode += 1
        # decrease epsilon
        epsilon = max(epsilon*eps_decay, eps_min)
                     
    return Q                

def test_policy(multi_env, Q, winner,num_episodes):
    score = np.zeros(num_episodes)
    multi_env.reset()
    i_episode = 0        
    # keeps iterating over active agents until num episode break
    while i_episode < num_episodes:
        if i_episode%100 == 0:
            print(i_episode)
        policy = {}
        for agent in multi_env.agent_iter():           
            # get observation (state) for current agent:
            observation, reward, done, info = multi_env.last()
            state = encode_state(observation['observation'])            
            if not done: 
                # choose action using epsilon_greedy_policy()
                if multi_env.agent_selection == winner:
                    epsilon = 0 # epsilon == 0 ==> deterministicly follow policy
                else:
                    epsilon = 1 # epsilon == 1 ==> random
                policy[agent] = make_epsilon_greedy_policy(Q[agent], epsilon, multi_env.action_spaces[agent].n) 
                action_probs = policy[agent](state,observation['action_mask'])
                action_probs = action_probs/sum(action_probs)
                action = np.random.choice(np.arange(len(action_probs)), p=action_probs)
                multi_env.step(action)
                #multi_env.render()                
            else: 
                # agent is done
                multi_env.step(None)
                #multi_env.render()                
        
        if reward != 0 : # nor draw
            if multi_env.agent_selection == 'player_2' : # player_1 wins
                score[i_episode] = 1
            else:
                score[i_episode] = -1


        multi_env.reset()
        
        # bump episode
        i_episode += 1
        
                     
    return score               



env = tictactoe_v3.env()

random.seed(123)

fullrun = 1

if fullrun:
    Q = marl_q_learning(env, 500, alpha = 0.6, gamma = 0.95)
    #pickle.dump( Q, open( "Q.pkl", "wb" ) )
    with open('Q.pkl', 'wb') as f:
        dill.dump(Q, f)
else:
    with open('Q.pkl', 'rb') as f:
        Q = dill.load(f)   


score1 = test_policy(env,Q,'player_1',3000)
score2 = test_policy(env,Q,'player_2',3000)
print(sum(score1==1))
print(sum(score2==1))

**Comment by benblack769** [comment]
If you import `dill` first, swapping the order of the imports of dill and pettingzoo, it works:

```
import dill
from pettingzoo.classic import tictactoe_v3
import random
import numpy as np
from collections import defaultdict
import hashlib
import pickle
import matplotlib.pyplot as plt
```

Very little clue why this works. I would suspect some sort of combination of the EzPickle hack and some oddities in dill?

Very weird.

**Comment by huameichen0523** [comment]
Yes, it works now.
Thank you very much.

Hua-mei
