### ISSUE TITLE
RLlib example using deprecated supersuit wraper

### ISSUE THREAD

**Issue by FelipeMartins96** [Farama-Foundation/PettingZoo#709]
https://github.com/Farama-Foundation/PettingZoo/blob/8a8e0403da237fe1cd389dcadaa7cfab8616dec1/tutorials/rllib_pistonball.py#L54
```
    raise DeprecatedWrapper(
supersuit.DeprecatedWrapper: resize_v0 is now deprecated, use resize_v1 instead
```

**Comment by jjshoots** [comment]
@FelipeMartins96, thanks for the report, do you mind making a PR addressing this issue? But if that's not possible, we're working on that and it should be up fairly soon.

**Comment by FelipeMartins96** [comment]
I can open the PR in a moment.
I could fix my tests as the warning is pretty self-explanatory :), just wanted to register here that it is outdated
