### ISSUE TITLE
[Proposal] Refactor Pytest multiple calls to a single call

### ISSUE THREAD

**Issue by kir0ul** [Farama-Foundation/PettingZoo#719]
### Proposal

I would suggest to rewrite the 7 calls to Pytest in [`release_test.sh`](https://github.com/Farama-Foundation/PettingZoo/blob/master/release_test.sh) to a single call.

### Motivation

I find the [current testing logs](https://github.com/Farama-Foundation/PettingZoo/runs/6713136740?check_suite_focus=true#step:6:1) pretty unreadable, instead of having to navigate between 7 different testing logs, it would be nice to have one single call to Pytest that recapitulates all the warnings, errors, and passed tests at the end.

### Pitch

I would suggest to remove the `release_test.sh` Bash script completely and simply call `pytest -v` which will run all of those tests in one call.

I've been told that this Bash script is useful to run only a subset of the tests by commenting the others. To me it seems easy enough to run any of those manually by writing for example `pytest ./test/variable_env_test.py` in the terminal, but if it is useful to people to have them separated and already written, then I would suggest to create a `Makefile` with those 7 commands to be run easily without having to comment anything into a Bash script.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo (**required**)

**Comment by jjshoots** [comment]
I'm in agreement with removing release test in favour of something more elegant, it's probably OK for you to go ahead and get this done. I see that SuperSuit doesn't have this funky release test thing as well.

**Comment by kir0ul** [comment]
@jjshoots (or anyone else), do you want me to actually add `make` commands to replace the calls in `release_test.sh`?

**Comment by jjshoots** [comment]
@kir0ul If we can consolidate it such that the file is no longer a thing, that would be good yes. Though I don't think using `make` would be a good idea, we already have enough dependencies for tests as is and people are bound to have problems. That said, if `make` is deemed superior, I'm open to reviewing what it would look like and may consider using that instead.

**Comment by kir0ul** [comment]
I don't know if it's superior, indeed it's a pretty old tool but it's one of the standard Linux tools. I guess I'll create a `Makefile` in a single commit so that you can test if you like it, and if not I'll just revert it.

**Comment by kir0ul** [comment]
So it's in this commit: https://github.com/Farama-Foundation/PettingZoo/pull/731/commits/2ab0f6974bfb811e67fc63c215bf9897e883c741.
You can install it with:
- Linux: `sudo apt install make` (depends on the distribution/package manager)
- MacOS: `brew install make`, they say the command should be available as `gmake` instead of `make` (https://formulae.brew.sh/formula/make)
- Windows: `choco install make` (https://community.chocolatey.org/packages/make)

Then `make help` should give all the available commands and you can use `Tab` when writing the command if it's too long to write:
```
clean                Clean tmp files
help                 Show this help
test-all-html        Run tests with HTML report, see `index.html` file in `htmlcov` folder
test-all             Run ALL tests
test-doc-examples    Run `doc_examples_test.py` tests
test-param-combs     Run `all_parameter_combs.py` tests
test-print           Run `print_test.py` tests
test-runner          Run `pytest_runner.py` tests
test-specific-env    Run `specific_env_tests.py` tests
test-unwrapped       Run `unwrapped_test.py` tests
test-variable-env    Run `variable_env_test.py` tests
```
So to run all the test, one would write `make test-all`.

**Comment by kir0ul** [comment]
I'll add the [previous comment](https://github.com/Farama-Foundation/PettingZoo/issues/719#issuecomment-1162624659) somewhere to the docs if we decide to keep it.

**Comment by kir0ul** [comment]
Fixed in https://github.com/Farama-Foundation/PettingZoo/pull/731.
