### ISSUE TITLE
PettingZoo Custom Parallel Env + StableBaselines3 error

### ISSUE THREAD

**Issue by frankiiie** [Farama-Foundation/PettingZoo#723]
Hello! I would like to implement a custom parallel environment using PettingZoo and then train multiple agents using StableBaselines3 and SuperSuit (for parameter sharing). For this, I’ve looked into some helpful references, such as the [13-line code tutorial](https://towardsdatascience.com/multi-agent-deep-reinforcement-learning-in-15-lines-of-code-using-pettingzoo-e0b963c0820b) and [Parallel API on your website](https://www.pettingzoo.ml/api#parallel-api). Unfortunately, I’m running into an error when running the [Example Custom Parallel Environment](https://www.pettingzoo.ml/environment_creation#example-custom-parallel-environment).

My code is as follows. The environment I'm trying out is the [Example Custom Parallel Environment](https://www.pettingzoo.ml/environment_creation#example-custom-parallel-environment).

```
from stable_baselines3 import DQN
import supersuit as ss
env = parallel_env()
env = ss.pettingzoo_env_to_vec_env_v1(env)
model = DQN('MlpPolicy', env)
model.learn(total_timesteps=10000)
```

I get the following error after reaching model.learn().
```
TypeError                                 Traceback (most recent call last)
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
[<ipython-input-11-c1ca84c8dd29>](https://localhost:8080/#) in <module>()
----> 1 model.learn(total_timesteps=10000)

5 frames
[/usr/local/lib/python3.7/dist-packages/stable_baselines3/common/vec_env/dummy_vec_env.py](https://localhost:8080/#) in _save_obs(self, env_idx, obs)
     90         for key in self.keys:
     91             if key is None:
---> 92                 self.buf_obs[key][env_idx] = obs
     93             else:
     94                 self.buf_obs[key][env_idx] = obs[key]

ValueError: setting an array element with a sequence.
```

I am not sure whether this error occurs due to version conflict, especially since I did not make any changes on the example custom parallel environment, or maybe I misunderstood something in my code.

Thank you in advance for your feedback.

**Comment by jjshoots** [comment]
Hiya, could you post the full stack trace here and report your version of gym, SB3, and PZ here?

**Comment by benblack769** [comment]
I belive the problem is that stable_baselines3 goes and does an `isinstance()` check to determine whether the environment is a stable_baselines3.VectorEnv or a regular gym env (default), so it incorrectly assumes the env is a gym env.

The concat_vec_envs wrapper has an argument that dynamically adds  a wrapper so that stable baselines knows it is a vector env:
```
from stable_baselines3 import DQN
import supersuit as ss
env = parallel_env()
env = ss.pettingzoo_env_to_vec_env_v1(env)
env = ss.concat_vec_envs_v1(env, 1, 1, base_class='stable_baselines3')
model = DQN('MlpPolicy', env)
model.learn(total_timesteps=10000)
```

**Comment by jjshoots** [comment]
@frankiiie does this solve your problem? Can it be closed?

**Comment by frankiiie** [comment]
Hello! Yes, the additional line solves the issue. Thanks a lot for your help!

Also, just to quickly confirm my understanding of how things work, the line "pettingzoo_env_to_vec_env_v1(env)" alone takes care of the parameter sharing for CTDE, or do I need to add something else? This is assuming a scenario where all the agents use the same RL algorithm, have the same observation and action spaces and step simultaneously (no addition/deletion of agents during training).

**Comment by jjshoots** [comment]
@frankiiie yes, essentially `pettingzoo_env_to_vec_env_v1(env)` converts an AEC environment into what Stable Baselines assumes is n set of environments. You do not need to do anything else to have parameter sharing.

**Comment by frankiiie** [comment]
Got it. Thank you!
