### ISSUE TITLE
[Question] Any progress with Atari Surround environment

### ISSUE THREAD

**Issue by quantumiracle** [Farama-Foundation/PettingZoo#727]
Hi, 

I was trying to solve some two-player Atari games for a while, and I created a [repo](https://github.com/quantumiracle/MARS) with some algorithms implemented, including Self-Play, Fictitious Self-Play and its neural network version, also the Policy Space Response Oracle with Double Oracle, based on DQN/PPO. But I found it hard to crack the Surround-v1 in Atari. Is there any suggestion for this problem, for generally boosting the exploration of the learning agents or others?

Any idea would be appreciated, thanks!

**Comment by jjshoots** [comment]
Hiya, so this isn't really a PZ issue, but rather an issue of how to make RL algorithms work better. There are generally a lot of things that can be done, though I don't know too many of them.

I recommend that you join the [official RL discord](https://discord.gg/JjuUACGn), and post your question there instead. :)

**Comment by quantumiracle** [comment]
Hi, sorry if it's not a proper place to ask about this:)

**Comment by benblack769** [comment]
I would also comment that learning Atari with self play is much more difficult than you might expect. In addition to all the single agent problems with Atari (sparse rewards, long histories, difficult observation space, etc), there are multiagent problems (non-stationarity, all agents get the same observation), and combinations of the two (neural network instability).

Numerous groups have tried and failed to learn reasonable policies. 

The best results I've seen so far are here https://wandb.ai/openrlbenchmark/openrlbenchmark/reports/Pettingzoo-s-Multi-agent-Atari-CleanRL-s-PPO--VmlldzoyMDkxNTE5

**Comment by quantumiracle** [comment]
Oh, interesting to see someone else's work on this problem. However, one thing to notice is that for multi-agent games (e.g. zero-sum games) the episode length may not be a proper metric to evaluate in the end. Ideally a policy close to Nash equilibrium should be achieved.

**Comment by benblack769** [comment]
@quantumiracle In general, absolutely. But it seems to be a decent approximation of success in surround specifically, as the screen fills up over time, and is way easier to measure than some sort of nash equilibira.
