### ISSUE TITLE
[Proposal] Change MPE rendering to use Pygame instead of pyglet

### ISSUE THREAD

**Issue by jjshoots** [Farama-Foundation/PettingZoo#732]
### Proposal

Currently MPE uses the outdated rendering engine Pyglet. It should be changed to Pygame as is done with the other environments.

**Comment by WillDudley** [comment]
Will look into this.

**Comment by WillDudley** [comment]
See PR at https://github.com/Farama-Foundation/PettingZoo/pull/738
