### ISSUE TITLE
[Bug Report] Environment initialization error

### ISSUE THREAD

**Issue by albinakl** [Farama-Foundation/PettingZoo#744]
I installed the latest 1.19.0 version of pettingzoo (pip and github cloning) to [colab](https://colab.research.google.com/drive/1Nt0umnAL4UkEge7yxCBoMoS2J_-3SABS?usp=sharing) and imported pong_v3 environment. However, when I tried to initialize the environment I got the following error:

env = pong_v3.env(num_players=2)

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-8-5d9a5ee49d6c>](https://localhost:8080/#) in <module>()
----> 1 env = pong_v3.env(num_players=2)

1 frames
[/usr/local/lib/python3.7/dist-packages/pettingzoo/atari/pong/pong.py](https://localhost:8080/#) in raw_env(num_players, game_version, **kwargs)
     36     name = os.path.basename(__file__).split(".")[0]
     37     parent_file = glob("./pettingzoo/atari/" + name + "*.py")
---> 38     version_num = parent_file[0].split("_")[-1].split(".")[0]
     39     name = name + "_" + version_num
     40     return BaseAtariEnv(

IndexError: list index out of range

Python 3.7.13
Google.Colab

Thx!

**Comment by Tenich** [comment]
Hi! Please try installing ROMs for ATARI (using [AutoROM](https://github.com/Farama-Foundation/AutoROM/)) and check whether the error persists.

**Comment by albinakl** [comment]
Thank you for your answer! I succeed in installation of 1.18.1 version of PettingZoo with working atari in colab. Here what I runned:

!pip install autorom[accept-rom-license]
!pip install pettingzoo[atari]==1.18.1
!AutoROM --accept-license

from pettingzoo.atari import pong_v3
import matplotlib.pyplot as plt
env = pong_v3.env(num_players=2)
env.reset()

screen = env.render(mode='rgb_array')
plt.imshow(screen)
