### ISSUE TITLE
[Bug Report] Broken atari environment path

### ISSUE THREAD

**Issue by manu-hoffmann** [Farama-Foundation/PettingZoo#746]
Hi!

I ran into the [same issue](https://github.com/Farama-Foundation/PettingZoo/issues/744) with PettingZoo version 1.19.
Found the issue to be a broken path in file `pettingzoo/atari/pong/pong.py`.

I fixed the issue by replacing line 37:

`parent_file = glob(os.path.join(os.path.dirname(os.path.dirname(__file__)), name + "*.py"))`

I don't think this is the best solution, but did the job for me.

Thanks.

**Comment by jjshoots** [comment]
Hi @manu-hoffmann, yes this is a currently known issue in PettingZoo which is why there has not been a new release yet. The developer who's supposed to fix this is kinda busy, if you would be so inclined, could you make a PR fixing this?

**Comment by manu-hoffmann** [comment]
Hi @jjshoots,

I just opened a PR for fixing this issue.
