### ISSUE TITLE
[Question] Where is the max_cycles coming from? Not in OpenAI repo.

### ISSUE THREAD

**Issue by aenneas** [Farama-Foundation/PettingZoo#752]
### Question
The documentation for MPE says:

 "The game terminates after the number of cycles specified by the max_cycles environment argument is executed. The default for all environments is 25 cycles, as in the original OpenAI source code."
 
 However, I could not find this anywhere in the original OpenAI source code. There is no fixed horizon, not even an argument. In fact, in the issues, Ryan Lowe says the done is always False, and they let the environments run forever even if the target is reached.

**Comment by jjshoots** [comment]
Hi, the max cycles for each environment is defined in the environment arguments, eg: [here](https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/mpe/simple_crypto/simple_crypto.py#L19) for simple_crypto and [here](https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/mpe/simple_reference/simple_reference.py#L12) for simple_reference.

In [here](https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/mpe/_mpe_utils/simple_env.py#L240), max cycles is used to set the dones for all the MPE environments.

Trying to find an issue depicting the exact thread you're describing is not ideal, could you perhaps link it with the relevant # instead?

**Comment by aenneas** [comment]
Hi,

This is not what I am referring to. I know where max_cycles are used and defined in the PettingZoo. 

If you look at the documentation here: https://www.pettingzoo.ml/mpe the claim is that:
"The game terminates after the number of cycles specified by the max_cycles environment argument is executed. The default for all environments is 25 cycles, **as in the original OpenAI source code.**"

However, no such default termination criteria exists in the original OpenAI source code (https://github.com/openai/multiagent-particle-envs). Nowhere. In addition to that, you can see here in their Issues (https://github.com/openai/multiagent-particle-envs/issues/13) that the first author of the original paper says they **do not terminate** the environment at all, and let it run forever.

**Comment by jjshoots** [comment]
Ah, I see what you mean, there is definitely some disconnect between how up to date the documentation is versus the codebase at hand, and a project for us to automate it to prevent these things in the future is ongoing. That said, if you want the behaviour of letting the environment run to infinite, you could simply set `max_cycles=np.inf` in the environment arguments, and that would achieve the same thing.

**Comment by aenneas** [comment]
Hi,

Thanks, setting max_cycles=np.inf is not an issue. What I would like to know is where the claim **"as in the original OpenAI source code"** is coming from. This would be useful for me to replicate their results since the details of episode length are left out in the paper.

**Comment by jjshoots** [comment]
Again, I reiterate, this library is not affiliated with OpenAI and the developers of that library, the work here is only a derivative of their work. As to your question, I do not have an immediate answer as I wasn't the main developer nor was I around to supervise the PR that added those envs in. You'll probably have more luck asking the authors of the paper themselves.

That said, if you find that the claim of 'as in the original OpenAI source code' is false, do let us know/open a PR fixing it, and we'll amend it accordingly.

**Comment by jjshoots** [comment]
Checking the git blame, it seems that the particular line in the docs is written by @benblack769, so perhaps he would have an answer to your question.

**Comment by aenneas** [comment]
> Again, I reiterate, this library is not affiliated with OpenAI and the developers of that library, the work here is only a derivative of their work. As to your question, I do not have an immediate answer as I wasn't the main developer nor was I around to supervise the PR that added those envs in. You'll probably have more luck asking the authors of the paper themselves for exact implementation details.
> 
> That said, if you find that the claim of 'as in the original OpenAI source code' is false, do let us know/open a PR fixing it, and we'll amend it accordingly.

I am asking where does that claim originate from, because I cannot find anything to back it up. This has nothing to do with the authors of the paper, it also has nothing to do with whether the library is affiliated to OpenAI or not. It is a very simple question: where does this claim in the **PettingZoo** documentation come from? I am also not directing my question to you specifically, I am asking it inside the repo, in general, assuming that the person who wrote that claim will clarify things for me. Now you mention that @benblack769 can clarify this, great. Thanks.

**Comment by benblack769** [comment]
@aenneas This came from the MADDPG paper, which in my understanding was developed concurrently with MPE, by the same authors.

You can see the number 25 [here](https://github.com/openai/maddpg#environment-options) and [here](https://github.com/openai/maddpg/blob/master/experiments/train.py#L15). You can also see reference to this forced reset of the environment in the `max-episode-length` of Algorithm 1 of the [MADDPG paper](https://arxiv.org/pdf/1706.02275.pdf), though a specific number is not given in the paper.

**Comment by aenneas** [comment]
@benblack769  Aaah I see, thanks a lot! Yes this makes sense, I am fairly confident in this case that they used 25. The performance they get seems in line with a good policy executed with max-episode-length 25 on average. I was looking for it in the original MPE repo, then got confused. Still cannot figure out how it is used in the original MPE repo since they don't have it anywhere in their code, and Ryan Lowe says done is always False forever in response to the issue, but I digress. 

Thanks for the clarification!
