### ISSUE TITLE
[Question] Possible bug in '_was_done_step' function in utils.AECEnv

### ISSUE THREAD

**Issue by chwflhs** [Farama-Foundation/PettingZoo#755]
### Question

location:
line 228 to line 237 in `_was_done_step` function in [utils/env.py](https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/utils/env.py).

I found this when I am reading the code but I have not tested it yet. It seems a bug from a point of logic:
The `self._skip_agent_selection` stores a `done = true` agent(which was dead and deleted).  Then how could it store a live agent as said in line 228 " loads next live agent (Stored in `_skip_agent_selection`)"?

============================This is the code==============================
```py
 def _was_done_step(self, action: None) -> None:

        if action is not None:
            raise ValueError("when an agent is done, the only valid action is None")

        # removes done agent
        agent = self.agent_selection   _**※→this agent is a "done agent"**_
        assert self.dones[
            agent
        ], "an agent that was not done as attempted to be removed"
        del self.dones[agent]
        del self.rewards[agent]
        del self._cumulative_rewards[agent]
        del self.infos[agent]
        self.agents.remove(agent)     # this agent is deleted!

        # finds next done agent or loads next live agent (Stored in _skip_agent_selection)
        _dones_order = [agent for agent in self.agents if self.dones[agent]]
        if _dones_order:
            if getattr(self, "_skip_agent_selection", None) is None:
                self._skip_agent_selection = self.agent_selection   # this self.agent_selection is pass to the _skip_agent_selection for the future usage!
            self.agent_selection = _dones_order[0]
        else:
            if getattr(self, "_skip_agent_selection", None) is not None:
                self.agent_selection = self._skip_agent_selection # how could _skip_agent_selection store a live agent since a Done agent is passed to it?
            self._skip_agent_selection = None
        self._clear_rewards() 
```

**Comment by jjshoots** [comment]
@benblack769 I believe this is your field.

**Comment by chwflhs** [comment]
I provide my solution to this problem for discussion. Two situations require consideration:
1. If len(_dones_order)== len(self.agents), in this case, there is no "live" agent so there is no need to change self.agent_selection
2. Otherwise, a random "live" agent could be chosen from the "undone set" for the self._skip_agent_selection.

Hence, the fix of the code is as follows: (only two lines (231-232) are changed)

        # finds next done agent or loads next live agent (Stored in _skip_agent_selection)
        _dones_order = [agent for agent in self.agents if self.dones[agent]]
        
        if _dones_order:
            if getattr(self, "_skip_agent_selection", None) is None and len(_dones_order)<len(self.agents): #fix
                self._skip_agent_selection = list(set(self.agents)-set(_dones_order))[0] #fix
            self.agent_selection = _dones_order[0]
        else:
            if getattr(self, "_skip_agent_selection", None) is not None:
                self.agent_selection = self._skip_agent_selection
            self._skip_agent_selection = None
        self._clear_rewards()

**Comment by benblack769** [comment]
This is an unfortunately confusing bit of logic, built essentially to remove some code duplication required interally to keep equivalence with the parallel env model. While I don't think there are any bugs here, I have been wrong before.

Also note that these are all internal helper functions to try to reduce code duplication that we found while developing new environments, especially the environments we wrote before creating the parallel_to_aec wrapper. If you have no need to support the parallel interface, there are certainly simpler ways of going about this.

With that out of the way, how things are supposed to work:

1. Env labels an agent as done
2. Rest of cycle continues as usual without interruption
3. Next cycle done agents are queued up first, to allow the handler code to read the done label.

I.e., you have 4 agents: A, B, C, D iterating in a cycle

A, B, C, D, all takes actions in cycle 1

Then after D moves, the environment updates and decides that agent B and D aredone.

Then the environment inner cycle will go:

A: done=False, C: done=False,

But the outer environment, with these utilis needs to also iterate through the done agents, so it does:

B: done=True, D: done=True, A: done=False, C: done=False,

In that order.

Note that this utility does need to store B and D and keep them around *after* they are done, so it can iterate though them and let the user know that they are done in the agent iteration loop. These are the values stored in _dones_order. Then it also needs to store the next agent that the environment implementation decides is next,  A, in this case. The base environment (without this utility) has set the agent_indicator=A, this utility stores that so it can resume at that agent after going through all the dead agents. So it stores that in `_skip_agent_selection`.

**Comment by chwflhs** [comment]
@benblack769 thanks for the reply, the key issue is how to set the agent_indicator (the pointer).  

The first thing is the agent_indicator should point to the undone set, which is A or C in the case. 

Second,  if A is already selected before B, then the agent_indicator should point to C instead of A ? 

#Since A, B, C, and D forms a cycled queue, the visiting sequence may have an influence. Of course, B and D are deleted after done.

**Comment by benblack769** [comment]
@chwflhs So I think it is generally preferable that the done agents should be visited before the other agents, though it is not technically, required, I think. Otherwise, it is really up to the designer of the algorithm. 

With this utility, the assumption is that the base implementation already has an idea of whether A or C should go first. It captures that preference by saving the env.agent_indicator, and then restoring it after finishing up with the done agents. So if the base implementation choose A to go next after D finishes, then this utility should help select A next after B and D iterate.

**Comment by chwflhs** [comment]
ok, thanks for your explanation.
