### ISSUE TITLE
[Bug Report] cannot import name 'Renderer' from 'magent'

### ISSUE THREAD

**Issue by hellofinch** [Farama-Foundation/PettingZoo#756]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
I try to change the environment based on this [script](https://github.com/ray-project/ray/blob/ray-1.13.0/rllib/examples/multi_agent_independent_learning.py). The origin script used waterworld which has bug so I change it to `magent.battle`. The output show below:
```

Traceback (most recent call last):
  File "rlpe.py", line 4, in <module>
    from pettingzoo.magent import battle_v4
  File "/anaconda3/envs/PettingZoo/lib/python3.7/site-packages/pettingzoo/magent/__init__.py", line 5, in __getattr__
    return deprecated_handler(env_name, __path__, __name__)
  File "/anaconda3/envs/PettingZoo/lib/python3.7/site-packages/pettingzoo/utils/deprecated_module.py", line 52, in deprecated_handler
    spec.loader.exec_module(module)
  File "/anaconda3/envs/PettingZoo/lib/python3.7/site-packages/pettingzoo/magent/battle_v4.py", line 1, in <module>
    from .battle.battle import env, parallel_env, raw_env  # noqa: F401
  File "/anaconda3/envs/PettingZoo/lib/python3.7/site-packages/pettingzoo/magent/battle/battle.py", line 7, in <module>
    from pettingzoo.magent.magent_env import magent_parallel_env, make_env
  File "/anaconda3/envs/PettingZoo/lib/python3.7/site-packages/pettingzoo/magent/magent_env.py", line 4, in <module>
    from magent import Renderer
ImportError: cannot import name 'Renderer' from 'magent' (/anaconda3/envs/PettingZoo/lib/python3.7/site-packages/magent/__init__.py)
```
**Code example**
```
from ray import tune
from ray.tune.registry import register_env
from ray.rllib.env.wrappers.pettingzoo_env import PettingZooEnv
from pettingzoo.magent import battle_v4

# Based on code from github.com/parametersharingmadrl/parametersharingmadrl

if __name__ == "__main__":
    # RDQN - Rainbow DQN
    # ADQN - Apex DQN
    def env_creator(args):
        return PettingZooEnv(battle_v4.env(map_size=45, minimap_mode=False, step_reward=-0.005,
dead_penalty=-0.1, attack_penalty=-0.1, attack_opponent_reward=0.2,
max_cycles=1000, extra_features=False))

    env = env_creator({})
    register_env("battle", env_creator)

    tune.run(
        "APEX_DDPG",
        stop={"episodes_total": 60000},
        checkpoint_freq=10,
        config={
            # Enviroment specific
            "env": "battle",
            # General
            "num_gpus": 1,
            "num_workers": 2,
            # Method specific
            "multiagent": {
                "policies": set(env.agents),
                "policy_mapping_fn": (lambda agent_id, episode, **kwargs: agent_id),
            },
        },
    )
```

**System Info**
Describe the characteristic of your environment:
Linux with conda and pip
Python 3.7.9
PettingZoo 1.20.1
supersuit 3.5.0
gym 0.22.0
**Additional context**

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo (**required**)

**Comment by jjshoots** [comment]
@dsctt could you have a look at this?

**Comment by benblack769** [comment]
What is the magent package version?

**Comment by hellofinch** [comment]
@benblack769 How can I know the version? I try `pettingzoo.magent.__version__` but it failed.

**Comment by jjshoots** [comment]
@hellofinch magent is a standalone package on pypi, try `pip3 show magent` in the terminal.

**Comment by Faris-Tulbah** [comment]
I'm facing this same issue when I try running:

!pip install pettingzoo[magnet]
!pip install magnet
from pettingzoo.magent import tiger_deer_v4

I get:

ImportError: cannot import name 'Renderer' from 'magent'

**Comment by benblack769** [comment]
0.1.13 is a very old version of MAgent. You should be able to upgrade your version to the most recent version with `pip install magent --upgrade` or `pip install magent==0.2.3`

Also watch out, if you installed the original, unmaintained magent package here https://github.com/geek-ai/MAgent, then you will need to manually uninstall it, which might be tricky.

**Comment by hellofinch** [comment]
I upgrade the`magent`.
```
Name: magent
Version: 0.2.3
Summary: Multi-Agent Reinforcement Learning environments with very large numbers of agents
Home-page: https://github.com/Farama-Foundation/MAgent
Author: Farama Foundation
Author-email: jkterry@farama.org
License: None
Location: /anaconda3/envs/PettingZoo/lib/python3.7/site-packages
Requires: numpy, pygame
Required-by:
```
And I try to run the script again and another error comes out.
```
Traceback (most recent call last):
  File "rlpe.py", line 31, in <module>
    "policies": set(env.agents),
AttributeError: 'PettingZooEnv' object has no attribute 'agents'
```

**Comment by WillDudley** [comment]
magent is depreciated

**Comment by hellofinch** [comment]
@WillDudley May I know why magent is depreciated? I think it is a good environment that has an invariable observation shape.
 If I want to use magent, what can I do?

**Comment by jjshoots** [comment]
@hellofinch Magent has not been deprecated, it's just been moved to its own repository because it deserves to have its own management team behind it. View it [here](https://github.com/Farama-Foundation/MAgent2) :).

**Comment by WillDudley** [comment]
We should add a warning to notify users of this. I'll add it to the list of things to do.

Thanks for the issue!

**Comment by dsctt** [comment]
> We should add a warning to notify users of this. I'll add it to the list of things to do.
> 
> Thanks for the issue!

#857
