### ISSUE TITLE
[Question] installable versions for tutorials

### ISSUE THREAD

**Issue by minarth** [Farama-Foundation/PettingZoo#757]
### Question

Hello, I am trying to follow your tutorial `tutorials/13_lines.py` and I am unable to figure out what versions of libraries should I install.  Since current versions of `pettingzoo`, `supersuit` and `stable-baselines3` has conflicting gym versions. Can anyone provide working `requirements.txt` for the tutorials?

Thank you :)

**Comment by jjshoots** [comment]
The latest PZ and SS versions should work with the latest SB3 version. You'll receive a warning about gym being incompatible, but things should otherwise work fine.

**Comment by minarth** [comment]
It would really be nice to have the `requirements.txt` with the tutorials so it is easy to navigate. Since I don't get warning, but error when installing. Also, the latest versions suffer from https://github.com/Farama-Foundation/SuperSuit/pull/165 where there is not enough clear info about what to do to solve it.  :(

**Comment by WillDudley** [comment]
Hey @minarth , thanks for your interest in PZ. We're currently finalising a big update, and hope to update/improve the tutorials after. 

Tomorrow (when I'm at my desktop) I'll get a minimal working repo of 13_lines spun up and will shoot it over your way :)

**Comment by WillDudley** [comment]
Unfortunately to get 13_lines.py working, SB3 needs to be updated to reflect the new overhaul we're having.

Getting it working using past versions of pz, ss and sb3 is unfortunately pretty tenuous. If you have any specific questions I'll try my best to help though.

**Comment by minarth** [comment]
@WillDudley thanks for trying. Looking forward to the big update and working setup : )

**Comment by WillDudley** [comment]
@minarth 

Tianshou appears to work but I haven't looked into it in much detail
https://github.com/WillDudley/Tianshou-MARL-Examples
