### ISSUE TITLE
[Proposal] Port All Environments to Parallel Env

### ISSUE THREAD

**Issue by jjshoots** [Farama-Foundation/PettingZoo#759]
According to Ben, in the near future during the wrappers revamp, it'd be better for us to port all environments to parallel env, and then use the parallel_to_aec wrapper.

**Comment by WillDudley** [comment]
This issue is probably a subset of https://github.com/Farama-Foundation/PettingZoo/issues/803

**Comment by jjshoots** [comment]
With PZ2, this will likely not be needed.
