### ISSUE TITLE
[Progress] Truncation/Termination/Rendering API Update

### ISSUE THREAD

**Issue by jjshoots** [Farama-Foundation/PettingZoo#769]
# About

As part of the Gym update to 0.25, the following changes have been made:

1. `done` -> `termination` and `truncation`
    - The singular `done` signal has been changed to a `termination` and `truncation` signal, where `termination` dictates that the environment has ended due to meeting certain conditions, and `truncation` dictates that the environment has ended due to exceeding the time/frame limit
2. "type" of rendering is determined at `init` and shouldn't be changed
    - This means you can recompute certain information for a render type
    - For `human`, the rendering happens inside step and render returns None and does nothing
    - For `rgb_array`, render returns a list of all renders since the last render call
    - For `single_rgb_array`, render returns the last render

## Progress

The road plan for this update is as follows:

1. Truncation/Termination update
    - [x] MPE
    - [x] MAgent
    - [x] Butterfly
    - [x] Atari
    - [x] SISL
    - [x] Classic
2. Tests update
    - [x] `all_parameter_combs_test.py`
        - [x] MPE
        - [x] MAgent
        - [x] Butterfly
        - [x] Atari
        - [x] SISL
        - [x] Classic
    - [x] `doc_example_test.py`
    - [x] `print_test.py`
    - [x] `pytest_runner_test.py`
    - [x] `specific_env_test.py`
    - [x] `unwrapped_test.py`
    - [x] `variable_env_test.py`
3. Supersuit update
4. Render update
5. Tests update
6. Supersuit update

**Comment by WillDudley** [comment]
@jjshoots This can be closed? Everything's done right?
