### ISSUE TITLE
[Question] Where can I find the best solution of th env in the PettingZoo?

### ISSUE THREAD

**Issue by pmy0721** [Farama-Foundation/PettingZoo#773]
Where can I find the best solution of th env in the PettingZoo? 
Just like the Leaderboard of gym.

**Comment by jjshoots** [comment]
@pmy0721 There currently is None, one reason for this is that PettingZoo is not a completely mature library yet, and the environments are still subject to minor changes. Having a leaderboard at this time would not be an ideal thing to do froma reproducibility standpoint.
