### ISSUE TITLE
[Question] Problem when rendering MPE environment headlessly

### ISSUE THREAD

**Issue by cciliber** [Farama-Foundation/PettingZoo#778]
### Question

Hi, I am running some PettingZoo environments on a remote machine (running Ubuntu) that has no display. I have no issues when rendering (to e.g. create a gif of a run of a trained policy) for environments such as the recommended `pistonball`, but when I switch to e.g. `simple_tag_v2`, I get the error  `pygame.error: No available video device` 

Do you have any advice?

**Comment by jjshoots** [comment]
Hiya, thanks for the report, I would try this:

```py
import os
os.environ["SDL_VIDEODRIVER"] = "dummy"
```

taken from [here](https://stackoverflow.com/questions/15933493/pygame-error-no-available-video-device)

**Comment by cciliber** [comment]
Thanks for the reply! I had indeed stumbled upon that stackoverflow post but unfortunately, it does not solve the issue: pygame simply renders to nothing: the resulting rgb vector is a black image for every frame. 

I tried using Xvfb to create a virtual X frame grabber but I am not that familiar with it to be able to make it work. : (  

Any idea why it does work with other environments?

**Comment by jjshoots** [comment]
@cciliber, can you comment on whether render itself works on your local machine (with a working monitor)?

**Comment by cciliber** [comment]
OK. I'll give it a go and get back to you.

**Comment by jjshoots** [comment]
Any progress with this? @cciliber

**Comment by cciliber** [comment]
Hi @jjshoots sorry for the delay. Yes the problem seems to persist also on a machine with a working monitor. 

Any suggestion?

**Comment by jjshoots** [comment]
Hi @cciliber, I'm getting some people to look at this now, do you think you could put your code for a minimal reproducible implementation here?

**Comment by cciliber** [comment]
Sure, here it is:

```python
import os

import supersuit as ss
from stable_baselines3 import PPO
from stable_baselines3.ppo import MlpPolicy

from pettingzoo.mpe import simple_tag_v2


import PIL

policy_name = "policy-simple-tag"
num_good=1
num_adversaries=1
num_obstacles=1
max_cycles=20
continuous_actions=False

env = simple_tag_v2.parallel_env(
    num_good=num_good,
    num_adversaries=num_adversaries,
    num_obstacles=num_obstacles,
    max_cycles=max_cycles,
    continuous_actions=continuous_actions
    )

env = ss.frame_stack_v1(env, 2)
env = ss.pad_observations_v0(env)
env = ss.pettingzoo_env_to_vec_env_v1(env)
env = ss.concat_vec_envs_v1(env, 8, num_cpus=4, base_class="stable_baselines3")

model = PPO(
    MlpPolicy,
    env,
    verbose=3,
    gamma=0.95,
    n_steps=256,
    ent_coef=0.0905168,
    learning_rate=0.00062211,
    vf_coef=0.042202,
    max_grad_norm=0.9,
    gae_lambda=0.99,
    n_epochs=5,
    clip_range=0.3,
    batch_size=256,
)
model.learn(total_timesteps=2000)
model.save(policy_name)

model = PPO.load(policy_name)


# Rendering

env = simple_tag_v2.env(
    num_good=num_good,
    num_adversaries=num_adversaries,
    num_obstacles=num_obstacles,
    max_cycles=max_cycles,
    continuous_actions=continuous_actions
    )
env = ss.frame_stack_v1(env, 2)
env = ss.pad_observations_v0(env)


env.reset()

frame_list = []
for agent in env.agent_iter():
    obs, reward, done, info = env.last()
    act = model.predict(obs, deterministic=True)[0] if not done else None
    env.step(act)
    frame_list.append(PIL.Image.fromarray(env.render(mode='rgb_array')))


frame_list[0].save("out-"+policy_name+".gif", save_all=True, append_images=frame_list[1:], duration=3, loop=0)
```


Admittedly it's not an MWE. Let me know if you need me to write one without model training.

**Comment by FilipinoGambino** [comment]
Hello @cciliber, thanks for the code. I'll take a look at it this weekend.

**Comment by WillDudley** [comment]
@FilipinoGambino Any updates on this?

**Comment by jjshoots** [comment]
Marking as solved, feel free to reopen if the issue persists. Thanks everyone for the help!
