### ISSUE TITLE
'numpy.random._generator.Generator' object has no attribute 'random_integers'

### ISSUE THREAD

**Issue by Himanshu1231** [Farama-Foundation/PettingZoo#783]
Getting this error while working with the following code:
**Code:**
from pettingzoo.butterfly import pistonball_v6
env = pistonball_v6.env()
env.reset()
for agent in env.agent_iter():
    observation, reward, done, info = env.last()
    action = policy(observation)
    env.step(action)

**Error:**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [17], in <cell line: 1>()
----> 1 env.reset()
      2 for agent in env.agent_iter():
      3     observation, reward, done, info = env.last()

File ~\anaconda3\lib\site-packages\pettingzoo\utils\wrappers\order_enforcing.py:94, in OrderEnforcingWrapper.reset(self, seed, return_info, options)
     92 self._has_reset = True
     93 self._has_updated = True
---> 94 super().reset(seed=seed, options=options)

File ~\anaconda3\lib\site-packages\pettingzoo\utils\wrappers\base.py:85, in BaseWrapper.reset(self, seed, return_info, options)
     84 def reset(self, seed=None, return_info=False, options=None):
---> 85     self.env.reset(seed=seed, options=options)
     87     self.agent_selection = self.env.agent_selection
     88     self.rewards = self.env.rewards

File ~\anaconda3\lib\site-packages\pettingzoo\utils\wrappers\base.py:85, in BaseWrapper.reset(self, seed, return_info, options)
     84 def reset(self, seed=None, return_info=False, options=None):
---> 85     self.env.reset(seed=seed, options=options)
     87     self.agent_selection = self.env.agent_selection
     88     self.rewards = self.env.rewards

File ~\anaconda3\lib\site-packages\pettingzoo\butterfly\pistonball\pistonball.py:353, in raw_env.reset(self, seed, return_info, options)
    351 vertical_offset_range = 15
    352 if self.random_drop:
--> 353     self.vertical_offset = self.np_random.random_integers(
    354         -vertical_offset_range, vertical_offset_range + 1
    355     )
    356     self.horizontal_offset = self.np_random.random_integers(
    357         -horizontal_offset_range, horizontal_offset_range + 1
    358     )
    359 ball_x = (
    360     self.screen_width
    361     - self.wall_width
   (...)
    364     + self.horizontal_offset
    365 )

AttributeError: 'numpy.random._generator.Generator' object has no attribute 'random_integers'

**Comment by jjshoots** [comment]
@pseudo-rnd-thoughts mind having a look?

**Comment by pseudo-rnd-thoughts** [comment]
That numpy function was deprecated and wouldn't be surprised if the function was finally removed. I think petting zoo needs to update to integers however the random number generator in petting zoo is not consistent

**Comment by jjshoots** [comment]
@Himanshu1231 I could solve this but I am without computer access for the next 2-3 days.

**Comment by 1860yk** [comment]
have the same issue.

**Comment by pseudo-rnd-thoughts** [comment]
This has already been fixed in https://github.com/Farama-Foundation/PettingZoo/pull/777
I guess we just need to make a new release with it included @jjshoots
