### ISSUE TITLE
[Proposal] A unified multi-agent environment API

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [Farama-Foundation/PettingZoo#803]
### Proposal

A new core API for PettingZoo (PZ) that is very similar to the Gym core API with several key advantages. However, this would require a large rewrite of the whole code base

```python
import pettingzoo as pz

env = pz.make("KnightArcherZombies-v10")
policies = {agent_name: policy, ...}

obs, info = env.reset(seed=10)
while env.active:
    actions = {agent_name: policies[agent_name](agent_obs) for agent_name, agent_obs in obs.items()}
    obs, rewards, terminations, truncations, info = env.step(actions)
env.close()
```

### Motivation

I have used Gym for 3/4 years and have recently been helping maintain it for the last 5/6 months so believe I have a strong understanding of that project. 

However, moving across to use PZ there are a number of things that are done differently from Gym making it **difficult** for new users to transition from single agent RL to multi-agent RL, which I believe are primarily caused by the API. 

Therefore, in discussions with @RedTachyon and @jjshoots, I have developed a minimal version of the proposed changes. 
These changes aim to
1. Increase incompatibility between Gym and PZ, particularly in terms of wrappers and training code
2. Increase API compatibility making it easier for users to change from Gym to PZ (along with code)
3. Reduce the complexity of the PZ core API (in particular remove the `AECEnv` and `ParallelEnv` in favour of a single core env API)
4. Easier maintenance of the environments, wrappers and training.
5. Add a Gym style registry with `make` and `register` functions

Priority additions
* Strict type hinting (stronger type hinting from Gym currently)
* Docstrings - Requirement for all functions to have docstrings

### Pitch

My proposal is to replace both the `AECEnv` and `ParallelEnv` with this `MultiAgentEnv` and a new Gym space called `Container`

```python
class MultiAgentEnv(ABC, Generic[ObsType, ActType]):
    """The main Multi-Agent API for environments."""

    metadata: dict[str, Any] = {}

    spec: EnvSpec | None = None
    render_mode: str | None = None

    observation_space: gym.Space[Any]
    action_space: gym.Space[Any]

    np_random: np.random.Generator

    episode_steps: int = -1
    max_episode_steps: Optional[int] = None

    active: bool = False

    is_closed: bool = False

    @abstractmethod
    def reset(
        self, *, seed: int | None = None, options: dict[str, Any] | None = None
    ) -> tuple[ObsType, dict[str, Any]]:
        """Reset function for multi-agent environments.

        Args:
            seed: The seed for the environment
            options: The options when resetting the environment

        Returns:
            A tuple of agent observations and environment information
        """
        pass

    @abstractmethod
    def step(
        self, actions: ActType
    ) -> tuple[
        ObsType,
        dict[str, SupportsFloat],
        dict[str, bool],
        dict[str, bool],
        dict[str, Any],
    ]:
        """Step function for transitioning through the environment.

        Args:
            actions: The action to take for the current agent

        Returns:
            A tuple of next agent's observations, the agent's rewards, termination, truncation and info.
        """
        pass

    def render(self) -> Any:
        """Visualises the environment depending on `render_mode`.

        Returns:
            Depending on the `render_mode` the visualised environment state
        """
        raise NotImplementedError
```

This core `MultiAgentEnv` is extremely similar to Gym's core `Env` class with a number of added parameters. 
The reason that this API can support multiple agents is that the observation may indicate all agents who must submit actions in the next step. This can be done with a dictionary of agent names and observations (see the `Container` space) allowing variable numbers of agents to take actions each step (allowing turned-based games or 100s of agents taking actions simultaneously taking actions at the same time or for agents to died and respawn through the game.). Alternative observation spaces are possible as well, such as for fixed agents number games to use `Dict` spaces for all agents (or compressed as a `Box`) or use a `Tuple` with observations with an agent indicator such as a multi-binary array for the current agent or a text field with the next agent's name. 

I believe this API can support all multi-agent (and single-agent) games.

The `reward`, `termination` and `truncation` variables are dictionaries (but could be made more flexible to allow simpler data) containing **all** agents in the last observation (and action). However in special cases, such as where an agent not taking an action terminated during the step, that agent must be included in all three variables. A simple example of this is Chess where only a single agent acts during each time step, however, once checkmated two agents are terminated therefore the reward, termination and truncation must contain both agents. 

 Two important new variables between the Gym core API and this proposed core API is
* `active` - As `terminated` doesn't show if the whole environment has terminated, just agents, then I propose using a new variable `active` (name is changeable) to show if the whole environment has terminated and `reset` needs to be called.
* `episode_steps` - Truncation is a critical but fairly unknown feature of modern RL, Gym recently added this more explicitly in v25 which is implemented using the `gym.wrappers.TimeLimit` wrapper. However, as multi-agent can define an episode differently (a full turn by all active players i.e. ludo or for each step in the environment), we have left this open to the environment to define. This is not a necessary attribute and could be replaced with wrappers in a similar aspect to Gym that are applied in `make`.

One of the critical assumptions of Gym is that all observations (and actions) are contained within their `observation_space` and `action_space`. Currently, Gym does not have a space that allows for a variable number of agents that can have different spaces.

I propose the `Container` space (this name can be changed). The space is very similar to the `gym.spaces.Dict` with the primary difference being the `sample` and `contains` functions. One of the critical advantages of this Space along with the same `reset` and `step` functions is that with some additional code it would be possible to implement almost all of the new Gymnasium wrappers (https://github.com/Farama-Foundation/Gymnasium/pull/22) into PettingZoo.
```python
class Container(
    gym.Space[Dict[str, Any]],
    Mapping[str, pettingzoo.Space[Any]],
):
    def __init__(
        self,
        spaces: dict[str, gym.Space[Any]] | None = None,
        seed: int | seeding.RandomNumberGenerator | None = None,
        **spaces_kwargs: gym.Space[Any],
    ):
        self.spaces: Dict[str, gym.Space[Any]] = {}
        if spaces is not None:
            assert isinstance(spaces, dict)
            for agent_id, space in spaces.items():
                assert isinstance(space, gym.Space)

                self.spaces[agent_id] = space

        for agent_id, space in spaces_kwargs.items():
            assert agent_id not in self.spaces
            assert isinstance(space, gym.Space)

            self.spaces[agent_id] = space

        super().__init__(shape=None, dtype=None, seed=seed)

    @property
    def is_np_flattenable(self) -> bool:
        """As the container has a variable size, then it is not possible to flatten the space to a fixed size."""
        return False

    def sample(
        self, mask: Optional[Union[Sequence[str], Dict[str, Any], int]] = None
    ) -> dict[str, Any]:
        """Sample from the container space with an optional mask.

        Args:
            mask: An optional mask for sampling from the Container space.
                - Collection[str] -> The sample is generated only for the strings in spaces
                - dict[str, Any] -> Sample for all keys with the values being the `space.sample`
                - int -> Randomly samples a number of the subspaces
                - None -> Randomly sample all spaces

        Returns:
            A sample that is contained within the space.
        """
        if mask is not None:
            if isinstance(mask, dict):
                assert all(agent in self.spaces for agent in mask.keys())
                return {
                    agent: self.spaces[agent].sample(agent_mask)
                    for agent, agent_mask in mask.items()
                }
            elif isinstance(mask, Sequence):
                assert all(agent in self.spaces for agent in mask)
                return {agent: self.spaces[agent].sample() for agent in mask}
            elif isinstance(mask, int):
                assert len(self.spaces) <= mask
                agents: list[str] = self.np_random.choice(
                    list(self.spaces.keys()), size=mask, replace=False
                )
                return {agent: self.spaces[agent].sample() for agent in agents}
            else:
                raise Exception(
                    f"Unknown mask type: {type(mask)}, expecting dict, Sequence or int."
                )

        return {key: space.sample() for key, space in self.spaces.items()}

    def contains(self, x: Any) -> bool:
        """Checks if `x` is contained with the Container space."""
        return isinstance(x, dict) and all(
            key in self.spaces and x[key] in self.spaces[key] for key in x.keys()
        )

    def __getitem__(self, __k: Any) -> pettingzoo.Space[Any]:
        """Gets an item in the space."""
        return self.spaces[__k]

    def __len__(self) -> int:
        """The length of the Container spaces."""
        return len(self.spaces)

    def __iter__(self) -> Iterator[str]:
        """Iterator through the Container spaces."""
        yield from self.spaces

    def __eq__(self, o: object) -> bool:
        """If the object `o` is equivalent to this Container."""
        return isinstance(o, Container) and o.spaces == self.spaces
``` 

An additional change is to implement a registration module with `make` and `register` functions. I have written a majority of this module, and if this proposal is of interest, I can add this code to the issue. The implementation is not identical to the Gym based version, as we do not need to be backward compatible and can remove a number of features that are not needed.

I suspect that I have not provided enough detail for the actual environment specifications, so please ask questions where I have not provided enough detail. 

If we were interested in implementing this change, this would be a multi-stage project. 
The first would be to make a new branch where this work would occur. I have written a major of the core API which we would start reviewing and testing. The second stage would be to start changing environment implementations to the new API. Along with this, would be to implement the Gymnasium wrappers noted above along with unique PZ wrappers.

**Comment by WillDudley** [comment]
SGTM. 

So, the only difference between a regular env and a multi-agent env would be that in `step()` and `reset()`, what's returned is a dict of all agent obs, truncs, terms, infos?

Wondering what the process would fully look like if one wanted to:
- convert a gym env to a PZ env
- convert a PZ env to a gym env

**Comment by pseudo-rnd-thoughts** [comment]
For converting Gym to PZ and PZ to Gym should be possible with wrappers that make minimal changes. 

To using the gym wrappers with the proposed api, it is a smaller subgroup than I originally thought with just all of the observation based lambda wrappers. However this is fairly large number of wrappers with the rest needing small updates.

**Comment by benblack769** [comment]
At one point I thought about termination/truncation for multi-agent and determined that some really powerful simplicities and type-enforced validation emerge if you assert that: 

* "termination" is *always* agent specific (all agents terminating does not imply and environment terminates), and
* "truncation" is *always* global to the environment (agents will never truncate individually).

Then, the user will be expected to be astute enough to know that an environment truncating and all agents terminating should be handled as the agents terminating, not truncating. 

Here is the basic reasoning:

* An agent truncating in the middle of an environment where other agents are still active will look very strange to the other agents. It will just freeze, not taking any more actions. Very strange stuff.
* An environment terminating isn't necessary---it can always just terminate all the agents, then truncate itself.

This removes the need for this `active` parameter, and many of the weird cases that start to emerge with agent-specific truncation.

**Comment by WillDudley** [comment]
Whilst I'm not fully clued-in to all the advantages of separating `done` into `terminate` and `truncate`, I thought it allowed for more flexible algorithm design. 

If it is indeed important for algorithms to have distinctions between the two, then having agents truncate at the end of an episode instead of terminate would be important. Otherwise, it wouldn't be trivial for a user coming from applying PPO on a gymnasium env to apply two PPOs on a dyadic PZ env.

Some researchers may want to give different agents different agent lifespans (I take the perspective of it's the agent that truncates, and the environment closes when all agents are inactive).

We could add warnings if agents truncate at different times, but the user is still granted the choice to do so if they wanted.

**Comment by jjshoots** [comment]
I also thought of having only an env-specific truncation flag as opposed to agent-specific, but my logic as to why I did it that way was this:

Imagine we have a perpetually long environment (like the RuneScape game), and the environment can accomodate many agents. Now assume that our environment has an interaction budget for each agent (or each agent that is connected to it). In this scenario, the truncation flag is then a friendly way to tell the learning algorithm to disconnect and go into a learning loop from the trajectory that is just generated, without causing the broken Markov assumption of the environment ending because the agent did nothing wrong.

Yes, this will create weird artifacts for other agents, such as neighbouring agents suddenly freezing or disappearing, but this is indifferent to how many games currently work IRL, there is a possibility that the next player suddenly disconnects.

That said, I think having agent-specific truncation flags is in general a good thing, because this is fundamentally the more flexible thing to do.

**Comment by benblack769** [comment]
@jjshoots Your Runescape thought experiment was also my original inspiration (well, NeuralMMO). 

@WillDudley @jjshoots I would reiterate my previous argument and add the following more theoretical analysis:

* There have to be at least one completely valid game state in the future for the value of an agent in a truncated state. Otherwise, this would make the value of that state ill-defined or at least unlearnable, as it can never be reached by any agent.
* So there can be no completely deterministic, environment state driven reason for truncation in theory (obviously in practice this can be fudged if that part of the state is hidden from the agent, i.e. a hidden counter). 
* Asymmetric truncation where one agent truncates and another does not is then also a problem, as the truncated agent would imagine that it would be continuing, but the other agents would observe that it does not, creating wildly inconsistent notions of what the value of the truncated agent is.
* Next, I argue that this theory is non-obvious to most users, and they will run the hazard of creating bizarre, inconsistent environments for some ad-hock reasons. We should share this knowledge about the nature of truncation via the types in this API (returning a single bool instead of a dict).

I also advocate for the user experience on the framework side.

How would you go about creating a complex, multi-agent system perhaps with central value estimation, perhaps with reward sharing or communication when agents can be truncated at any time? Seems highly non-obvious to me. How would you go about broadcasting a bool to a dict if you need to in your implementation? `{agent: trunc for agent in agents}`. Pretty easy.

**Comment by jjshoots** [comment]
Thinking about it more, what @benblack769 has mentioned actually makes a lot of sense. A lot of funky race condition things happen with individual truncation flags.

**Comment by pseudo-rnd-thoughts** [comment]
I agree with @benblack769 and @jjshoots that the truncation flag can be a bool values not a dictionary. 
My only issue is implementing truncation in turn based (AECEnv) games, here we need each agent to individually take an action and after a turn they all truncate but maybe that is possible. More theoretical thought is required I think.

Secondly, @benblack769  I don't think we can remove the `active` parameter for one of the reasons that you gave. If all agents terminate in a step, this doesn't mean that the environment has terminated. Therefore, how do you know if to keep calling `step`? I guess you could have your observations being `None` to imply this but this breaks one of the assumptions that all observations are contained within the observation space.
Therefore, we can't use the observations or termination values to know when to stop calling `step`. Truncated does this but we need a case for termination. I considered have a special agent, "env" in the termination dictionary that could imply this but I thought that a simple environment attribute is better. What are your thoughts ?

**Comment by benblack769** [comment]
@pseudo-rnd-thoughts The `active` parameter can be replaced by the truncation bool. When the environment is truncated, we know it is time to reset.

**Comment by benblack769** [comment]
As for AEC games, we don't have to deal with this annoying "return the last observation/reward" stuff after a truncation, only after termination. In truncation, unlike termination, you can take your last action fully expecting to take another action, receiving another reward, observation, etc, you just never actually get to see it, because the environment has just stopped. 

```
A <- observation, reward, terminate=False, truncate=False
A -> action
B <- observation, reward, terminate=False, truncate=True
B -> action
# A,B does not need to know the result of their action, they will be estimating it, 
# because they know they haven't terminated yet.
```

If you combine this idea with the above idea of signaling `active` with truncation, and you want your environment to end after all agents have terminated, then your AEC loop would look something like this:

```
A <- observation, reward, terminate=False, truncate=False
A -> action
B <- observation, reward, terminate=False, truncate=False
B -> action
A <- final_obs, final reward, terminate=True, truncate=False
B <- final_obs, final reward, terminate=True, truncate=True
```

**Comment by benblack769** [comment]
^ Note that in a typical parallel environment, this all implies that the environment will usually terminate all the agents, and also truncate all in the same step. If you think that this will be super error prone to use, then I am open to that, but I get the feeling that people will quickly learn how to handle this case, as it is very common.

The alternative, where you have to consider `active`, `truncate`, and `termination` and figure out how the 3 of them should be playing with each other seems far more confusing.

**Comment by pseudo-rnd-thoughts** [comment]
@benblack769 I think we understand termination and truncation differently. 
At least in Gym, we use `termination` to refer to an agent reaching a terminating state (both success or fail states) given conditions within the environment. 
While truncation refers to if an episode will end prematurely due to a condition outside of the environment's terminating conditions. This is almost solely due to a time limit parameter but to the agent they cannot be aware of not continuing. Therefore in value bootstrapping, in a truncated state, the termination value is `False`. 

With the new API `done = terminated or truncated` compared to the old step API.

For PZ in parallel games, I agree, that all agents should be truncated at the same time so a bool value could be used
However, in the turned based games, as the next observation for an agent cannot be known after a step. I think it is easier to implement with a dictionary.

An example two player turn based game
- reset -> `player_1_obs`
- player 1 (`player_1_action`) -> `player_2_obs`, `truncated=False`
- player 2 (`player_2_action`) -> `player_1_obs`, `truncated=False`
- player 1 (`player_1_action`) -> `player_2_obs`, `truncated={"player_1": True}`
- player 2 (`player_2_action`) -> `player_1_obs`, truncated={"player_2": True}`, `active=False`

In this case, we need to lose the last two observations from both agents we don't have the next observation for either agent which is made more clear with a dictionary specifying the particular agent.
This is particularly helpful in cases with more than 2 agents where one of the agents terminates earlier in the episode, at which point, we need to remember which agents have already been terminated. 
Therefore, I think it is both clearer and easier to use a dictionary that can specify which agents have truncated at each time step.

**Comment by RedTachyon** [comment]
Can you describe what exactly is the difference between this API and the current parallel API? 

Also, what exactly is the point of `Container` as opposed to `Dict`? My understanding of the code is that it only requires a subset of agents to be present, is that right? I think it would be helpful to position this proposal in the context of what is already present, because the devil lies in the details.


We also have to precisely define the scope of "environments" that is meant to be representable as a PettingZoo environment. Should it support turn-based situations? Destroying and spawning agents during the episode? A destroyed agent respawning? I feel like the current proposal doesn't outline this sufficiently

**Comment by pseudo-rnd-thoughts** [comment]
The difference in API is primarily in the code, my aim is the support all multi-agent environments (that I can think of) with a single environment specification that is as similar as possible to Gym's specification as we can. 

The point of the `Container` space is that I want to keep the Gym assumption that all observations are contained within the observation space. In environments with variable numbers of agents acting at each time step or for parallel environments where agents die then you can't use `Dict` spaces. You could use the `Sequence` space but this doesn't allow different observation spaces for each agent. `Container` is a solution for all of these problems following a `Dict` like space where only a subset of the keys are needed for an observation.

For examples environments Im going to assume all environment use a Container space for simplicity but alternative spaces are possible. The code is not proper python as I have "opened up" for readers to have a easier way of see the variable types

* Turned based
```python
env.observation_space = Container(agent_1=..., agent_2=...)

{agent_1: obs}, info = env.reset()
{agent_2: next_obs}, {agent_1: reward}, {agent_1: terminated}, {agent_1: truncated}, info = env.step(agent_1_action)
{agent_1: next_obs}, {agent_2: reward}, {agent_2: terminated}, {agent_2: truncated}, info = env.step(agent_2_action)
{}, {agent_1: reward, agent_2: reward}, {agent_1: True, agent_2: True}, {agent_1: False, agent_2: False}, info = env.step(agent_1_action)  # Agent 1 causes the environment to terminate, i.e. a player being checkmate in chess 
env.active == False 
```

For parallel environments, with the `Container` space, the number of agents in each observation can increase or decrease over time steps allowing agents to "died" and "respawn" during an episode
```python
env.observation_space = Container(agent_1=..., agent_2=...)

{agent_1: obs, agent_2: obs}, info = env.reset()
{agent_2: next_obs}, {agent_1: reward, agent_2: reward}, {agent_1: True, agent_2: False}, {agent_1: False, agent_2: False}, info = env.step(agent_1_2_action)
{agent_1: next_obs, agent_2: next_obs}, {agent_2: reward}, {agent_2: False}, {agent_2: False}, info = env.step(agent_2_action)
...
```

I hope this helps, we can make a experimental branch and try to implement the ideas with example problems for each to see if it works

**Comment by benblack769** [comment]
@pseudo-rnd-thoughts Right, this rethinking/overloading of the "truncation" as "environment done" is certainly a divergence from gym's conception of it.   Perhaps being different than gym isn't ideal, but to me, the alternative of having 3 flags to worry about when reasoning about done-ness is worse.  A way to mitigate the situation is to just use a different naming scheme for this flag, and not call it truncation at all, but something to differentiate it.

In this AEC example of a two player turn based game, 

```
reset -> player_1_obs
player 1 (player_1_action) -> player_2_obs, truncated=False
player 2 (player_2_action) -> player_1_obs, truncated=False
player 1 (player_1_action) -> player_2_obs, truncated={"player_1": True}
player 2 (player_2_action) -> player_1_obs, truncated={"player_2": True}, active=False
```

To me it seems as if the truncation information given to player 1 is entirely redundant, as there is no possible valid way that player 1 would not be truncated if player 1 has not been terminated and the environment stops in the next step. 

Additionally, active=False also seems redundant. Once agents start getting truncated, they cannot produce any more actions, and so the environment *has* to shut down before that agent needs to take another action.

Redundant information leaves unnecessary room for errors on both sides of the API.

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for that. Yes, you are correct. If we make the assumption that all agents in the last observation are truncated then we can have truncated as a boolean variable. 

As for `terminated` / `active`, how should this be handled? 
I think there are two problems
1. How to handle when the environment not just individual agents? 
2. How to iterate through the environment? With Gym done is a clear variable for this but as `terminated` is a dictionary, it is not clear when this is true? Do we use `done = all(agent_terminated for agent, agent_terminated in terminated.items())`? 
For me, having a flag for the whole environment has terminated is a helpful flag when programming as it might not be clear when you have multiple agents dying and respawning but I might be wrong, I haven't done much MARL before.

**Comment by benblack769** [comment]
@pseudo-rnd-thoughts In my mind, `truncated` would be a bool, avoiding the problem.

**Comment by WillDudley** [comment]
This discussion has got quite deep, which is great, but I'm struggling to follow it. But, I very much agree with the motivation to make the API as similar to Gymnasium as possible, and especially combining AECEnv and ParallelEnv into one. Personally, coming from gym, AECEnv has always been more difficult to grasp than ParallelEnv.

I have some questions to get me more on the same page:
Are we adding active or not?
Is truncation going to be agent specific?
Why is the dict space not suitable for agents potentially dying?

**Comment by pseudo-rnd-thoughts** [comment]
@WillDudley No worries, I think the easier way is to make an experimental version and work out some of these details when programming
1. I think so, we should experiment with it and see if it works as a feature
2. No, I think that Ben is right that when `truncated` is `true` we know all of the agents if the `obs` have `truncated`
3. The gym dictionary space requires the observation to contain all subspaces observations. However, if agents are dying then we needs a variable size version of the dictionary space. This has the assumption that all observations must be in the observation space.

**Comment by jjshoots** [comment]
AFAICT the only reason we need a 'space' for all agents is so we can do `.sample()` to get all agents' observation/actions at the same time right? Imho this is a pretty rare use case, and I quite liked the dictionary style approach of the parallel env, where all the rewards, observations, terminations are handled as dicts. From this paradigm, if I were a new user, having the action space and observation space defined as a dict would also make very intuitive sense.

Essentially what I'm saying is that this introduction of the `Container` space represents an unnecessary abstraction to me. It's just a dictionary with a special caveat of being variable sized and having masking. I would be much more warm to the approach if we fixed the existing dictionary space to have variable sizes, this is then more inline with the native Python dictionary where a dictionary can have keys deleted.

It may just be me on this camp, but at the moment I'm only mildly lukewarm to the idea of the `Container` idea.

**Comment by WillDudley** [comment]
> @WillDudley No worries, I think the easier way is to make an experimental version and work out some of these details when programming
> 1. I think so, we should experiment with it and see if it works as a feature
> 2. No, I think that Ben is right that when `truncated` is `true` we know all of the agents if the `obs` have `truncated`
> 3. The gym dictionary space requires the observation to contain all subspaces observations. However, if agents are dying then we needs a variable size version of the dictionary space. This has the assumption that all observations must be in the observation space. 

@pseudo-rnd-thoughts 

3. Is it not possible to add a flag to the dictionary space to allow for agents dying? In my opinion that would be simpler for users to understand?

**Comment by WillDudley** [comment]
It seems like @jjshoots and I commented the same idea at the same time, I'm similarly yet to be convinced on `Container`, but open to being convinced.

What's going on with https://github.com/openai/gym/pull/2958 btw? Does the outcome of that affect this proposal?

**Comment by jjshoots** [comment]
That's primarily my issue with it, it's just a new space for a special subset of environments. Now there will be Dict spaces and Container spaces that are both valid for PZ, which is a problem, obfuscating easy of implementation for someone new to the API. And IIRC, the only environment with variable number of agents during runtime is KAZ (for now).

I'd honestly try harder to use existing tools or remove existing tools before adding new abstractions like this. A valuable lesson to learn all this from is SB3's own SB3_env wrapper for gym and pettingzoo wrappers. It's only needed for a subset of things and for a few very specific reasons, but because of its implementation, a whole host of other problems arise.

**Comment by WillDudley** [comment]
@pseudo-rnd-thoughts Maybe you could outline how ugly the refactor if we were to go through with refactoring the dict space?

**Comment by pseudo-rnd-thoughts** [comment]
@jjshoots That is a fair criticism, I thought there were more environments that had this issue

@WillDudley It would be possible to change the `Dict`, it just feels like to me having two spaces in one and @jjshoots criticism would still apply. In short, we would need to a new attribute, `optional_subspaces: bool` that would modify the `sample`, `contains` and `seed` functions to do different things depending on the value.

As I explained on a call to @WillDudley yesterday, I want to carry over the Gym assumption that **all** observation / actions are contained within their respective space. Therefore, with variable numbers of agents at each time step then a space like this would be important

**Comment by pseudo-rnd-thoughts** [comment]
This would violate the assumption as contains would be false. 

I think we are spending too much time focusing on a more minor part of the proposal that can be added or removed in the future. 

Therefore in the meantime, @WillDudley and I are going to try and make a working version in a private github repo

**Comment by ffelten** [comment]
Hi there, do you guys have any time horizon for this? I guess the functional APIs also change the game in this matter?

**Comment by pseudo-rnd-thoughts** [comment]
There is no active work on this so I'm going to close this to avoid confusion
