### ISSUE TITLE
[Proposal] Add tutorials to CI

### ISSUE THREAD

**Issue by WillDudley** [Farama-Foundation/PettingZoo#813]
Update:

I've added CI for the CleanRL tutorial here: https://github.com/Farama-Foundation/PettingZoo/pull/831

Tianshou and Ray tutorials still need to be debugged as they fail for import reasons.

**Comment by jjshoots** [comment]
How do we want to do this? Have a script that runs all the files in the tutorials folder? Also I think the readme in the tutorials can be deleted.

**Comment by WillDudley** [comment]
Yeah I'm thinking that. Also a script to check that PZ is the latest PyPi version.

@mgoulao ideally the docs, including the tutorials, would be version controlled, similar to https://numpy.org/doc/stable/ . Is this do-able?

**Comment by WillDudley** [comment]
https://github.com/WillDudley/PettingZoo/pull/1
