### ISSUE TITLE
[Proposal] Action masking in docs

### ISSUE THREAD

**Issue by WillDudley** [Farama-Foundation/PettingZoo#820]
In PZ env creation, there is a conventional way to apply action masking. I think it's only done in AECEnvs (eg. RLCard) but can easily be applied to ParallelEnvs for someone proficient in Gymnasium/PZ.

It will be a common feature in custom envs so the conventional way to implement it should be explained.

The cleanrl (and potentially other) tutorials would need to be extended to account for this.

**Comment by elliottower** [comment]
Just saw this now but we've added documentation for AEC envs, but it should be extended to parallel envs for consistency. Will change the title of this to reflect that.
