### ISSUE TITLE
[Bug Report] Parallel environment raises error when created with `gym.make`

### ISSUE THREAD

**Issue by rohin-dasari** [Farama-Foundation/PettingZoo#849]
### Describe the bug

When using `gym.make` to create a environment, gym uses a `PassiveEnvChecker` which makes the assertion that the `action_space` attribute of the environment object must inherit from `gym.spaces.Space`. In the parallel petting zoo environment, however, `action_space` is a method, which takes in a agent id as a parameter and returns the action space for that specific agent: https://pettingzoo.farama.org/api/parallel/#pettingzoo.utils.env.ParallelEnv.action_space

Here is the relevant traceback:
```
File "/work/gym_pcgrl/wrappers/parallel_multiagent_wrappers.py", line 180, in __init__
  self.pcgrl_env = gym.make(game, **kwargs)
File "/home/ray/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py", line 669, in make
  env = PassiveEnvChecker(env)
File "/home/ray/anaconda3/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 23, in __init__
check_action_space(env.action_space)
File "/home/ray/anaconda3/lib/python3.7/site-packages/gym/utils/passive_env_checker.py", line 75, in check_space
f"{space_type} space does not inherit from `gym.spaces.Space`, actual type: {type(space)}" 
AssertionError: action space does not inherit from `gym.spaces.Space`, actual type: <class 'method'>
```

Is this a common issue others have seen? Is there an established workaround?

### System info

The version of gym I am using is 0.26.2
The version of pettingzoo I am using is 1.22.1
Python version is 3.7.13

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by rohin-dasari** [comment]
Update: I was able to fix this by downgrading my version of gym to 0.21.0 (which doesn't have the environment checking feature). Maybe it still deserves to be an issue though since the `setup.py` file on the master branch of the pettingzoo repo explicity mentions that is requires a version of gym greater than 0.26.0.
https://github.com/Farama-Foundation/PettingZoo/blob/50579c60f35c12a5dcb29fb2279a2bde3a7efb8f/setup.py#L87

**Comment by WillDudley** [comment]
Hi @rohin-dasari , please may you share your code, specifically what environment you're using? It seems like the env action space isn't a Gymnasium space. Even if 0.21.0 doesn't catch this, it would still probably cause issues later.

**Comment by rohin-dasari** [comment]
Here's a minimal example that reproduces the issue: 
```python
import gym
from gym.envs.registration import register
from ray.rllib.env.wrappers.pettingzoo_env import PettingZooEnv
from pettingzoo import ParallelEnv
from gym import spaces


class CustomEnv(ParallelEnv):
    def __init__(self):
        self.agents = list(range(2))
        self.possible_agents = self.agents
        self.observation_spaces = {agent: spaces.Discrete(2) for agent in self.agents}
        self.action_spaces = {agent: spaces.Discrete(2) for agent in self.agents}

    def observation_space(self, agent):
        return self.observation_spaces[agent]

    def action_space(self, agent):
        return self.action_spaces[agent]

    def state(self):
        pass

    def reset(self):
        pass

    def step(self, actions):
        pass

if __name__ == "__main__":

    env = CustomEnv()
    register(id='env-v0', entry_point=CustomEnv)
    gym.make('env-v0')
```
Basically, the `action_space` attribute in the `ParallelEnv` api is a method that returns the action space for a particular agent. The gym passive environment checker expects this to be something that inherits from `gym.spaces.Space`.

**Comment by RedTachyon** [comment]
Is registering PZ envs via `gym.register` something that's commonly used/recommended? I'm pretty sure that's not supposed to be done ever, but I haven't looked at the PZ code in a while

**Comment by WillDudley** [comment]
Correct. Registration isn't implemented at all for PettingZoo.

**Comment by rohin-dasari** [comment]
Ah, that explains it then. I'll go ahead and close the issue.

**Comment by strakam** [comment]
why doesnt `pettingzoo` have similar registration procedure? Is there a specific reason im missing? 

I feel like it would be very similar to gym and it also would be nicer if it was more unified with Gymnasium.
