### ISSUE TITLE
[Bug Report] Parallel render function immediately crashes

### ISSUE THREAD

**Issue by dschonholtz** [Farama-Foundation/PettingZoo#860]
### Describe the bug

When trying to call the render function to see what the environment looks like with a parallel environment the environment crashes with an error saying int object isn't callable.
See code example and additional context for code snippet and exact stack trace.

I am fairly new to this library so if I'm doing something wrong that's my mistake I would be happy to fix it locally, but this seems right.

### Code example

```shell
from pettingzoo.mpe import simple_spread_v2

env = simple_spread_v2.parallel_env(N=3, local_ratio=0.5, max_cycles=25, continuous_actions=False)
env.reset()

env.render()
```

### System info

Installed with pip.
Running in a jupyter notebook.

pettingzoo version: 1.22.1
Running ubuntu 22.04
Python 3.10.6

### Additional context

TypeError                                 Traceback (most recent call last)
Cell In [13], line 3
      1 env.reset()
----> 3 env.render()
      5 while env.agents:
      6     actions = {agent: env.action_space(agent).sample() for agent in env.agents}  # this is where you would insert your policy

File ~/classes/RL/project/CS5180-project/venv/lib/python3.10/site-packages/pettingzoo/utils/conversions.py:177, in aec_to_parallel_wrapper.render(self)
    176 def render(self):
--> 177     return self.aec_env.render()

File ~/classes/RL/project/CS5180-project/venv/lib/python3.10/site-packages/pettingzoo/utils/wrappers/order_enforcing.py:64, in OrderEnforcingWrapper.render(self)
     62     EnvLogger.error_render_before_reset()
     63 self._has_rendered = True
---> 64 return super().render()

File ~/classes/RL/project/CS5180-project/venv/lib/python3.10/site-packages/pettingzoo/utils/wrappers/base.py:88, in BaseWrapper.render(self)
     87 def render(self):
---> 88     return self.env.render()

File ~/classes/RL/project/CS5180-project/venv/lib/python3.10/site-packages/pettingzoo/utils/wrappers/base.py:88, in BaseWrapper.render(self)
     87 def render(self):
---> 88     return self.env.render()
...
    274         )
    275         return
    277     self.enable_render(self.render_mode)

TypeError: 'int' object is not callable

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by WillDudley** [comment]
Hi there @dschonholtz ,

This is our bad! The int error is a bug that was fixed in `v1.22.2`. However, your code still isn't correct. If you look at the object that was trying to be called, you would see `WARN: You are calling render method without specifying any render mode.`. So the correct code would be

```py
from pettingzoo.mpe import simple_spread_v2

env = simple_spread_v2.parallel_env(N=3, local_ratio=0.5, max_cycles=25, continuous_actions=False, render_mode='human')
env.reset()

env.render()
```

I hope this helps, let us know if you have any other Qs by either reopening this issue or reaching out to us via Discord :)
