### ISSUE TITLE
[Bug Report] 'rgb_render' mode in MPE produces a black screen

### ISSUE THREAD

**Issue by bergem1t** [Farama-Foundation/PettingZoo#864]
### Describe the bug

When calling env.render() on an MPE environment with `rgb_array` render mode, I get a black screen. I tested it with `simple_v2` and 'simple_adversary_v2'. It does work with `connect_four_v3`.
It works for MPEs if I call the function `draw()`. `draw()` is called in `render()` for `human` but not `rgb_array` mode.

### Code example

```shell
from pettingzoo.mpe import simple_v2
from matplotlib import pyplot as plt


env = simple_v2.env(render_mode='rgb_array')

env.reset()
#env.env.env.draw() <--- works if uncommented
plt.figure; plt.imshow(env.render())
```

### System info

pip installed pettingzoo version 1.22.2
Windows 11
python 3.9.13

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by cibeah** [comment]
Hello,

I encountered the same issue. Indeed in the `render` method of `SimpleEnv` (mpe/_mpe_utils)/simple_env.py) which serves as base class for other MPE envs, the numpy array for the `rgb_array` version is rendered as a screen grab of the pygame screen, but the image is only drawn on the screen when mode is `human`. Incidentally the screen grab function is called in all cases even when it seems not needed.

`observation = np.array(pygame.surfarray.pixels3d(self.screen))
if self.render_mode == "human":
    self.draw()
    pygame.display.flip()
return (
    np.transpose(observation, axes=(1, 0, 2))
    if self.render_mode == "rgb_array"
    else None
)
`
Maybe we could have something like:

`
if self.render_mode == "rgb_array":
    observation = np.array(pygame.surfarray.pixels3d(self.screen))
    return np.transpose(observation, axes=(1, 0, 2))
if self.render_mode == "human":  
    pygame.display.flip()
return None
`
I can make a PR, but not sure if this is not already being fixed.

**Comment by WillDudley** [comment]
> Hello,
> 
> I encountered the same issue. Indeed in the `render` method of `SimpleEnv` ([mpe/_mpe_utils/simple_env.py, line 279](https://github.com/Farama-Foundation/PettingZoo/blob/bbf00ccacc6dea3a1f746f885b8f871c2890bfe0/pettingzoo/mpe/_mpe_utils/simple_env.py#L279)) which serves as base class for other MPE envs, the numpy array for the `rgb_array` version is rendered as a screen grab of the pygame screen, but the image is only drawn on the screen when mode is `human`. Incidentally the screen grab function is called in all cases even when it seems not needed.
> 
> Code:
> ```
> observation = np.array(pygame.surfarray.pixels3d(self.screen))
> if self.render_mode == "human":
>     self.draw()
>     pygame.display.flip()
> return (
>     np.transpose(observation, axes=(1, 0, 2))
>     if self.render_mode == "rgb_array"
>     else None
> )
> ```
> Maybe we could have something like:
> 
> ```
> self.draw()
> if self.render_mode == "rgb_array":
>     observation = np.array(pygame.surfarray.pixels3d(self.screen))
>     return np.transpose(observation, axes=(1, 0, 2))
> if self.render_mode == "human":  
>     pygame.display.flip()
> return None
> ```
> I can make a PR, but not sure if this is not already being fixed.

This isn't currently being fixed due to lack of resources - we'd greatly appreciate a PR :)
