### ISSUE TITLE
[Proposal] Improve AssertOutOfBoundWrapper to support MultiDiscrete spaces

### ISSUE THREAD

**Issue by opocaj92** [Farama-Foundation/PettingZoo#866]
### Proposal

When using this wrapper in a piece of code, I noticed that it only works for `Discrete` spaces from `gym`. However, extending it to `MultiDiscrete` spaces too is extremely straightforward: everything needed is to add a case to the assert check on `line 11` in `assert_out_of_bounds.py`:

`

        assert all(

            (isinstance(self.action_space(agent), Discrete) or isinstance(self.action_space(agent), MultiDiscrete))

            for agent in getattr(self, "possible_agents", [])

        ), "should only use AssertOutOfBoundsWrapper for Discrete spaces"
`

MultiDiscrete spaces has the same `contains()` method of Discrete ones, used in the `step()` method, so no further adjustment would be needed.

### Motivation

MultiDiscrete spaces are supported by many stable-baselines algorithms, and are useful in many situations.

### Pitch

The wrapper is useful in many situation, and having it to work with this kind of space as well would be really good.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by elliottower** [comment]
@opocaj92 sorry for the huge delay but if you’re still interested in this we would be happy to accept a PR.
