### ISSUE TITLE
[Proposal] Support `python3.11`

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Farama-Foundation/PettingZoo#871]
### Proposal

support `python3.11`

### Motivation

3.11 is the latest stable python release, 

`Gymnasium` already supports it

we need it for `Gymnasium-Robotics/MaMuJoCo` to support 3.11

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by WillDudley** [comment]
WIP @ https://github.com/Farama-Foundation/PettingZoo/pull/873

Thanks for the suggestion & any debugging help with this PR would be appreciated

**Comment by elliottower** [comment]
@WillDudley Is debugging help still needed? I'd be happy to help if needed, have something I'd like to test which requires 3.11

**Comment by elliottower** [comment]
Closing this as it works with our tutorial and other CI tests, if any users have issues with training or otherwise feel free to reopen
