### ISSUE TITLE
[Question] parallel_api_test

### ISSUE THREAD

**Issue by KevinJeon** [Farama-Foundation/PettingZoo#881]
### Question

Hi, I want to ask that line 120 of parallel_api_test

I got error of `AssertionError: ['agent_0', 'agent_1', 'agent_2'] != set()`
I found it occurs when my custom env is done!
![image](https://user-images.githubusercontent.com/49419937/215052632-015d5771-6ed0-4610-bb05-5b4dc8a75a0a.png)

```
f"{par_env.agents} != {live_agents}"
```

Why should "par_env.agents == live_agents"? and how can I fix it?

thanks!

**Comment by KevinJeon** [comment]
Oh, I find removing self.agent in AEC env code using `self._was_dead_step` function! 

Then, Should I recover the self.agent whenever I reset the env? `env.reset()`

Thks!

**Comment by pseudo-rnd-thoughts** [comment]
@WillDudley or @jjshoots Do you know the answer?

**Comment by benblack769** [comment]
Confirmed that the tutorial code fails the API test.

**Comment by benblack769** [comment]
The tutorial can be fixed with something like this:
```
        if self.timestep > 100:
            rewards = {"prisoner": 0, "guard": 0}
            truncations = {"prisoner": True, "guard": True}
            self.agents = []
```
@WillDudley @jjshoots
