### ISSUE TITLE
Different arguments setup between documentation and base file in waterworld_v4

### ISSUE THREAD

**Issue by george-skal** [Farama-Foundation/PettingZoo#884]
### Question

Hello, I noticed that the arguments for waterworld are different in the documentation in farama.org and in the waterworld_base.py in github, having some different speeds, n_coop etc. Is one of the two setups better or prefereable?
Also having different setups between documentation and code, can be misleading in case you don't define every argument on your code, in my opinion.
Please let me know about your thoughts.

Thanks,
George

**Comment by pseudo-rnd-thoughts** [comment]
@jjshoots or @WillDudley

**Comment by jjshoots** [comment]
Hi @george-skal, apologies for the confusion, the docstring didn't get updated when we performed a major overhaul of the environment. I'll get fix for this out now which will be in the next release. In the meantime, you can refer to [this](https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/sisl/waterworld/waterworld_base.py#L17).

**Comment by george-skal** [comment]
Hi @jjshoots. Thanks for your reply. I wanted also to ask you some more things, since on the previous versions I think there were some problems.
1. I notice that now n_coop=1 compared to 2 on previous versions. Isn't this making the environment not cooperative?
2. Also, n_pursuers=2 now, compared to 5 in the previous versions. I ask because I was using v3 having some problems on learning efficiency, but with n_coop=2 and n_pursuers=5. Is there a specific reason affecting performance for the reduction that you made? If I want to use 5 or 10 pursuers would it be too much for the environment in terms of spacing etc? Should I do other changes in that case?
3. I don't see something regarding render modes on documentation, but on the code I see 'human' and 'rgb_array' modes. Do you know if I can find information somewhere regarding that?
Thanks,
George

**Comment by jjshoots** [comment]
Hi @george-skal:
1. Yes, the environment is now competitive. However, as this is an argument, you're free to change this to observe more interesting behaviours.
2. The choice of reduction in n_coop and n_pursuers, like you mentioned, is a purely performance oriented thing. The environment will still work with the old parameters, but learning would take much longer and the environment will get very crowded. We find that the current parameters produces sufficiently interesting default behaviours, as seen [here](http://jjshoots.ddns.net:8090/share/dGv1E188).
3. The relevant code for render is [here](https://github.com/Farama-Foundation/PettingZoo/blob/master/pettingzoo/sisl/waterworld/waterworld_base.py#L714).

**Comment by george-skal** [comment]
Hi @jjshoots .

Thanks for the gifs, I understand what you mean. I would like to use 4 agents, so I think my only choice would be to decrease radius and also decrease poisons number, in order to be less crowded. Do you have any other proposals that could help with that? I suppose there is no way to increase the environment space/map size and the base environment needs to be modified.
