### ISSUE TITLE
[Question] How to retreive the docstring of a particular environment?

### ISSUE THREAD

**Issue by mbchang** [Farama-Foundation/PettingZoo#959]
### Question

I want to retrieve the docstring of a particular environment (e.g. the string [here](https://github.com/Farama-Foundation/PettingZoo/blob/8e99a1326c7f6da322a2fafb08c8776a785efcba/pettingzoo/classic/tictactoe/tictactoe.py#L2-L70) for example).

In gymnasium, I was able to retrieve the docstring as follows:
```
def get_docs(env):
    while 'env' in dir(env):
        env = env.env
    return env.__doc__

env = gym.make("Blackjack-v1")
docstring = get_docs(env)
```
However, if I do the same in the PettingZoo environments, `get_docs` returns `None`. I spot-checked this for `connect_four_v3`, `tictactoe_v3`, and `cooperative_pong_v5`. 

I was able to get the docstring in a very hacky way:
```
import inspect
from pettingzoo.classic.tictactoe import tictactoe

# Get the source code of the tictactoe module
source_code = inspect.getsource(tictactoe)

# Extract the file-level docstring by splitting the source code by triple quotes (""")
docstring = source_code.split('"""')[1]

# Print the docstring
print(docstring)
```
but this would require me to know what file actually implements the environment that I care about. In particular, I needed to use the file path `pettingzoo/classic/tictactoe/tictactoe.py` instead of the file path `pettingzoo/classic/tictactoe_v3.py`. I assume that the `tictactoe_v3` is the one intended to be the user-facing file, but I do not know how to get the docstring of `tictactoe` from that.

What is the best way for me to get the docstring of a PettingZoo env, from within python?

**Comment by mbchang** [comment]
Suggested label: "documentation"

**Comment by elliottower** [comment]
If you are looking for a given class docstring I believe you should be able to do it the same way as in gymnasium (https://github.com/Farama-Foundation/Gymnasium/blob/e3c5bd9df4640fe52a9f3184f764278631c43fc7/docs/scripts/gen_mds.py#L46), but for the file docstring I’m not sure if it’s possible.

**Comment by mbchang** [comment]
Thanks for your response. This method for getting class docstring does not work unfortunately:
```
>>> from pettingzoo.classic import tictactoe_v3
>>> env = tictactoe_v3.env()
>>> print(env.unwrapped.__doc__)
>>> None
```

**Comment by RedTachyon** [comment]
I posted it on Discord, but adding here for searchability. Yes, it's hacky because PZ structure is a bit hacky, but it should work. You might need to vary the details based on the env (e.g. whether you need the `aec_env` part)

```python
print(inspect.getmodule(env.aec_env.unwrapped).__doc__)
```

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/19414946/235534622-a7800b55-f81b-473a-af75-df40fa79dc24.png">

**Comment by mbchang** [comment]
Thank you! Should I expect that the PZ structure would continue to be like this?

**Comment by elliottower** [comment]
> Thank you! Should I expect that the PZ structure would continue to be like this?

Missed this but yes it can be assumed to stay with this structure
