### ISSUE TITLE
[Bug Report] Coop Pong v5 Action Space Sample Out of Bounds

### ISSUE THREAD

**Issue by zaptrem** [Farama-Foundation/PettingZoo#961]
### Describe the bug

Sampling from the action space of Coop Pong v5 results in an out of bounds error. Also, the docs have not been updated to v4 and still point to deprecated v4. I'm on 1.22.4.

### Code example

```shell
from pettingzoo.butterfly import cooperative_pong_v5

env = cooperative_pong_v5.env(ball_speed=9, left_paddle_speed=12,
right_paddle_speed=12, cake_paddle=True, max_cycles=900, bounce_randomness=True, max_reward=100, off_screen_penalty=-10)

env.reset()

screens = []
while env.agents:
    screen = env.render()
    screens.append(screen)
    actions = {agent: env.action_space(agent).sample() for agent in env.agents}  # this is where you would insert your policy
    print("action ", actions[env.agents[0]])
    observations, rewards, terminations, truncations, infos = env.step(actions)


```
action  2
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-7-173a902f4ae9> in <cell line: 30>()
     33     actions = {agent: env.action_space(agent).sample() for agent in env.agents}  # this is where you would insert your policy
     34     print("action ", actions[env.agents[0]])
---> 35     observations, rewards, terminations, truncations, infos = env.step(actions)
     36 # # prev_screen = env.render()
     37 # # plt.imshow(prev_screen)

2 frames
/usr/local/lib/python3.10/dist-packages/pettingzoo/utils/wrappers/assert_out_of_bounds.py in step(self, action)
     16     def step(self, action):
     17         assert (
---> 18             action is None
     19             and (
     20                 self.terminations[self.agent_selection]

AssertionError: action is not in action space
```
```

### System info

Python is 3.10
PettingZoo commands:
!pip install pettingzoo==1.22.4
!pip install pettingzoo[atari]==1.22.4
!pip install pettingzoo[butterfly]==1.22.4

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/PettingZoo/issues) in the repo

**Comment by elliottower** [comment]
Thanks for bringing this up, I’ll try to fix it

**Comment by elliottower** [comment]
Ah I see the issue, you're using parallel actions, when your env is an AEC env. Changing the code to call `cooperative_pong_v5.parallel_env()` makes your code work correctly.
